//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AStaffType
    {
        public string STAFF_TYPE { get; set; }
        public string STAFF_TYPE_NAME { get; set; }
        public string DEFAULT_ATT_GROUP { get; set; }
        public int STAFF_TYPE_SEQ { get; set; }
        public string YN_A01 { get; set; }
        public string YN_A02 { get; set; }
        public string YN_A03 { get; set; }
        public string YN_A04 { get; set; }
        public string YN_A05 { get; set; }
        public string YN_A06 { get; set; }
        public string YN_A07 { get; set; }
        public string YN_SALARY { get; set; }
    }
}
