//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPDBtestEntities : DbContext
    {
        public TPDBtestEntities()
            : base("name=TPDBtestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DT311_ACode> DT311_ACode { get; set; }
        public virtual DbSet<DT311_AStaffType> DT311_AStaffType { get; set; }
        public virtual DbSet<DT311_ATitle> DT311_ATitle { get; set; }
    }
}
