//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RU_TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACT_RU_TASK()
        {
            this.ACT_RU_IDENTITYLINK = new HashSet<ACT_RU_IDENTITYLINK>();
        }
    
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string PARENT_TASK_ID_ { get; set; }
        public string DESCRIPTION_ { get; set; }
        public string TASK_DEF_KEY_ { get; set; }
        public string OWNER_ { get; set; }
        public string ASSIGNEE_ { get; set; }
        public string DELEGATION_ { get; set; }
        public Nullable<int> PRIORITY_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> DUE_DATE_ { get; set; }
        public string CATEGORY_ { get; set; }
        public Nullable<int> SUSPENSION_STATE_ { get; set; }
        public string TENANT_ID_ { get; set; }
        public string FORM_KEY_ { get; set; }
    
        public virtual ACT_RE_PROCDEF ACT_RE_PROCDEF { get; set; }
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION { get; set; }
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACT_RU_IDENTITYLINK> ACT_RU_IDENTITYLINK { get; set; }
    }
}
