//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_EVT_LOG
    {
        public decimal LOG_NR_ { get; set; }
        public string TYPE_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string TASK_ID_ { get; set; }
        public System.DateTime TIME_STAMP_ { get; set; }
        public string USER_ID_ { get; set; }
        public byte[] DATA_ { get; set; }
        public string LOCK_OWNER_ { get; set; }
        public Nullable<System.DateTime> LOCK_TIME_ { get; set; }
        public Nullable<byte> IS_PROCESSED_ { get; set; }
    }
}
