//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_COMMENT
    {
        public string ID_ { get; set; }
        public string TYPE_ { get; set; }
        public System.DateTime TIME_ { get; set; }
        public string USER_ID_ { get; set; }
        public string TASK_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string ACTION_ { get; set; }
        public string MESSAGE_ { get; set; }
        public byte[] FULL_MSG_ { get; set; }
    }
}
