//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RE_DEPLOYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACT_RE_DEPLOYMENT()
        {
            this.ACT_GE_BYTEARRAY = new HashSet<ACT_GE_BYTEARRAY>();
            this.ACT_RE_MODEL = new HashSet<ACT_RE_MODEL>();
        }
    
        public string ID_ { get; set; }
        public string NAME_ { get; set; }
        public string CATEGORY_ { get; set; }
        public string TENANT_ID_ { get; set; }
        public Nullable<System.DateTime> DEPLOY_TIME_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACT_GE_BYTEARRAY> ACT_GE_BYTEARRAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODEL { get; set; }
    }
}
