//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RU_JOB
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string TYPE_ { get; set; }
        public Nullable<System.DateTime> LOCK_EXP_TIME_ { get; set; }
        public string LOCK_OWNER_ { get; set; }
        public Nullable<bool> EXCLUSIVE_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string PROCESS_INSTANCE_ID_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public Nullable<int> RETRIES_ { get; set; }
        public string EXCEPTION_STACK_ID_ { get; set; }
        public string EXCEPTION_MSG_ { get; set; }
        public Nullable<System.DateTime> DUEDATE_ { get; set; }
        public string REPEAT_ { get; set; }
        public string HANDLER_TYPE_ { get; set; }
        public string HANDLER_CFG_ { get; set; }
        public string TENANT_ID_ { get; set; }
    
        public virtual ACT_GE_BYTEARRAY ACT_GE_BYTEARRAY { get; set; }
    }
}
