//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RE_MODEL
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string NAME_ { get; set; }
        public string KEY_ { get; set; }
        public string CATEGORY_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_TIME_ { get; set; }
        public Nullable<int> VERSION_ { get; set; }
        public string META_INFO_ { get; set; }
        public string DEPLOYMENT_ID_ { get; set; }
        public string EDITOR_SOURCE_VALUE_ID_ { get; set; }
        public string EDITOR_SOURCE_EXTRA_VALUE_ID_ { get; set; }
        public string TENANT_ID_ { get; set; }
    
        public virtual ACT_GE_BYTEARRAY ACT_GE_BYTEARRAY { get; set; }
        public virtual ACT_GE_BYTEARRAY ACT_GE_BYTEARRAY1 { get; set; }
        public virtual ACT_RE_DEPLOYMENT ACT_RE_DEPLOYMENT { get; set; }
    }
}
