//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINGROUPITEM
    {
        public string GROUP_UID { get; set; }
        public string GROUPITEM_UID { get; set; }
        public string GROUPITEM_TYPE { get; set; }
        public string MEMBER_UID { get; set; }
        public string GROUPITEM_NAME { get; set; }
        public string GROUPITEM_NAME_E { get; set; }
        public string MAIN_UNIT { get; set; }
        public string POWER_OF_LEADER { get; set; }
        public string GROUPITEM_ID { get; set; }
        public Nullable<int> DISPLAY_ORDER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string titlecode { get; set; }
        public string titlename { get; set; }
        public string rolecode { get; set; }
        public string rolename { get; set; }
        public string Org_ID { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
