//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINGROUP
    {
        public string GROUP_UID { get; set; }
        public string GROUP_ID { get; set; }
        public string GROUP_TYPE { get; set; }
        public string PARENT_GROUP_UID { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_NAME_E { get; set; }
        public Nullable<int> DISPLAY_ORDER { get; set; }
        public string GROUP_TOP_UID { get; set; }
        public Nullable<int> GROUP_TREE_LEVEL { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string org_id { get; set; }
        public string GROUP_FULL_NAME { get; set; }
        public string DEPT_GROUP_ID { get; set; }
        public string DEPT_GROUP_NAME { get; set; }
        public string DEPT_AREA { get; set; }
        public string DEPT_EN_SHORT_CODE { get; set; }
    }
}
