//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmMenu
    {
        public int NodeID { get; set; }
        public string TaskTypeID { get; set; }
        public string NodeType { get; set; }
        public string NodeText { get; set; }
        public int ParentNodeID { get; set; }
        public int SortOrder { get; set; }
        public string PathName { get; set; }
        public string NavigateURL { get; set; }
        public string Target { get; set; }
        public int MenuLevel { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
