//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D307550000_basic
    {
        public string empuid { get; set; }
        public string eformid { get; set; }
        public string basic_profile { get; set; }
        public string fieldid { get; set; }
        public string @operator { get; set; }
        public string search_value { get; set; }
        public string search_end { get; set; }
    }
}
