//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AErrandFeeFormDetail
    {
        public string EFORMSN { get; set; }
        public int SN { get; set; }
        public string ERRAND_YEAR { get; set; }
        public string ERRAND_MONTH { get; set; }
        public string ERRAND_DAY { get; set; }
        public string START_END_PLACE { get; set; }
        public string TASK_DSCPT { get; set; }
        public Nullable<int> AIRPLANE_FEE { get; set; }
        public Nullable<int> CAR_FEE { get; set; }
        public Nullable<int> TRAIN_FEE { get; set; }
        public Nullable<int> SHIP_FEE { get; set; }
        public Nullable<int> LODGING_FEE { get; set; }
        public Nullable<int> LODGING_AND_TRAFFIC_FEE { get; set; }
        public Nullable<int> MEAL_FEE { get; set; }
        public Nullable<int> RECEIPTS_QTY { get; set; }
        public Nullable<int> LODGING_FREE_TIMES { get; set; }
        public Nullable<int> MEAL_FREE_TIMES { get; set; }
    }
}
