//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CCarInfo
    {
        public string CAR_NO { get; set; }
        public string SOURCE { get; set; }
        public string APPROVE_DAOCU { get; set; }
        public string BUY_DATE { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string LICENSE_DATE { get; set; }
        public string START_USE_DATE { get; set; }
        public string ENGINE_NO { get; set; }
        public string SCHDL_TEST_DATE { get; set; }
        public string BRAND { get; set; }
        public Nullable<int> REG_YEAR { get; set; }
        public string LICENSE_NO { get; set; }
        public string TYPE { get; set; }
        public int ENGINE_VOLUME { get; set; }
        public string REPORT_OBSOL_DATE { get; set; }
        public string YN_USE { get; set; }
        public string CAR_KEEPER_EMP_CODE { get; set; }
        public Nullable<decimal> OIL_USE_STD { get; set; }
        public Nullable<int> OIL_USE_VAR { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> SEAT { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
