//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DTRemit_Group
    {
        public string Remit_Group_Code { get; set; }
        public string Remit_Date { get; set; }
        public string Remiter { get; set; }
        public decimal Remit_Amount { get; set; }
        public string FormNO { get; set; }
        public string Keyin_Date { get; set; }
        public string Form_Type { get; set; }
    }
}
