//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DTempOVReportSum
    {
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public int BATCH { get; set; }
        public int OVERTIME_FEE_STAFF_TYPE { get; set; }
        public string OVERTIME_FEE_STAFF_TYPENAME { get; set; }
        public string EFORMSN { get; set; }
        public int TAMOUNT { get; set; }
        public int TRANS_AMOUNT { get; set; }
        public int CASH_AMOUNT { get; set; }
    }
}
