//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_COilInfo
    {
        public string CAR_NO { get; set; }
        public string USE_OIL_DATE { get; set; }
        public string OIL_TYPE { get; set; }
        public string DESTINATION { get; set; }
        public string DRIVE_JOB { get; set; }
        public string FILLING_EMP_CODE { get; set; }
        public Nullable<int> MILEAGE { get; set; }
        public Nullable<decimal> OIL_QTY { get; set; }
        public string END_OF_FILLING { get; set; }
        public string MGR_CHK { get; set; }
        public string UPDATE_STAFF { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
