//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVUpdateRec
    {
        public int OVERTIME_FEE_YEAR { get; set; }
        public int OVERTIME_FEE_MONTH { get; set; }
        public string DEPT_GROUP_CODE { get; set; }
        public string DEPT_GROUP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public int STAFF_TYPE { get; set; }
        public string ORG_EFORMSN { get; set; }
        public string ORG_FORM_TYPE { get; set; }
        public decimal BEF_UPD_TOTPAY { get; set; }
        public decimal BEF_UPD_REMNANTFEE { get; set; }
        public decimal BEF_UPD_MONTH_HAPPENFEE { get; set; }
        public decimal AFT_UPD_TOTPAY { get; set; }
        public decimal AFT_UPD_REMNANTFEE { get; set; }
        public decimal AFT_UPD_MONTH_HAPPENFEE { get; set; }
        public decimal UPDATE_DIF { get; set; }
        public int UPDATE_REASON { get; set; }
        public string UPDATE_EMP_CODE { get; set; }
        public string UPDATE_EMP_NAME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
