//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AAttCond
    {
        public int RECORD_NO { get; set; }
        public string ATT_GROUP { get; set; }
        public string VAC_TYPE { get; set; }
        public string PARA_1 { get; set; }
        public string PARA_2 { get; set; }
        public string MAX_DAYS { get; set; }
        public string ATT_REMARK { get; set; }
    }
}
