//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DPAY_INFO_R
    {
        public string PAY_CODE { get; set; }
        public string BATCH_NO { get; set; }
        public int recNO { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public int Amount { get; set; }
        public string BANK_ACCOUNT_H { get; set; }
        public string BANK_ACCOUNT_E { get; set; }
        public string BANK_TYPE { get; set; }
        public string BANK_CODE { get; set; }
        public int Fee { get; set; }
        public string memo { get; set; }
        public string update_staff { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
