//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_EMMSAssistant
    {
        public decimal SEQ_NO { get; set; }
        public string ORG_HANDLER_CD { get; set; }
        public string ORG_HANDLER_NM { get; set; }
        public string ASSIST_TYPE_CD { get; set; }
        public string ASSIST_TYPE_NM { get; set; }
        public string MMS_ASSIST_CD { get; set; }
        public string MMS_ASSIST_NM { get; set; }
        public string UPD_EMP_CODE { get; set; }
        public string UPD_DT_TM { get; set; }
        public string START_DTTM { get; set; }
        public string END_DTTM { get; set; }
    }
}
