//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVReportSum
    {
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public int BATCH { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public int OVERTIME_FEE_STAFF_TYPE { get; set; }
        public string OVERTIME_FEE_STAFF_TYPENAME { get; set; }
        public string EFORMSN { get; set; }
        public string FORM_STATUS { get; set; }
        public int Budget_YEAR { get; set; }
        public string BudgetNo { get; set; }
        public string BudgetName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string SubprojectNo { get; set; }
        public string SubprojectName { get; set; }
        public string ObjectNo_1 { get; set; }
        public string ObjectName_1 { get; set; }
        public string ObjectNo_2 { get; set; }
        public string ObjectName_2 { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectName { get; set; }
        public int TAMOUNT { get; set; }
        public int TRANS_AMOUNT { get; set; }
        public int CASH_AMOUNT { get; set; }
        public string REMARK { get; set; }
        public string FORM_CREATE_DATE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string CHIEF_SUID { get; set; }
        public string ATT_MANAGER_SUID { get; set; }
        public string ATT_DIRECTOR_SUID { get; set; }
        public string ACC_AUDITOR_SUID { get; set; }
        public string ACC_DIRECTOR_SUID { get; set; }
        public string ORG_REPR_SUID { get; set; }
    }
}
