//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AUnRestOTPay
    {
        public int RECORD_NO { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string EMP_CODE { get; set; }
        public string REPORT_GROUP { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string EMP_NAME { get; set; }
        public string STAFF_TYPE { get; set; }
        public string TITLE_NAME { get; set; }
        public string SALARY_GRADE_NAME { get; set; }
        public int BASE_SALARY { get; set; }
        public int ORPRFAMT { get; set; }
        public int BOSS_ADD { get; set; }
        public int MONTH_SALARY { get; set; }
        public decimal ADVANCE_DAYS { get; set; }
        public decimal ZSY_HOLIDAY_RESV_DAYS { get; set; }
        public decimal LY_HOLIDAY_RESV_DAYS { get; set; }
        public decimal BLY_HOLIDAY_RESV_DAYS { get; set; }
        public decimal SHOULD_OFF_DAYS { get; set; }
        public decimal ALREADY_OFF_DAYS { get; set; }
        public decimal UN_OFF_DAYS { get; set; }
        public decimal UN_REST_OVERTIME_FEE_DAYS { get; set; }
        public int UN_REST_OVERTIME_FEE { get; set; }
        public decimal HOLIDAY_SUBSIDY_DAYS { get; set; }
        public int HOLIDAY_SUBSIDY { get; set; }
        public int SHOULD_RECEIVE_AMOUNT { get; set; }
        public string QUIT_OR_RETIRE { get; set; }
        public string QUIT_OR_RETIRE_DATE { get; set; }
        public string EFORMSN { get; set; }
        public Nullable<decimal> ZSY_HOLIDAY_DAYS { get; set; }
    }
}
