//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DAccountSet
    {
        public int Account_YEAR { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public int MARRY_SUBSIDY { get; set; }
        public int BIRTH_SUBSIDY { get; set; }
        public int FUNERAL_SUBSIDY { get; set; }
        public int DEBIT_CHILDREN_EDU_SUBSIDY { get; set; }
        public int CANCELED_CHILDREN_EDU_SUBSIDY { get; set; }
        public int UNDEBIT_CHILDREN_EDU_SUBSIDY { get; set; }
        public int GENE_EMP_OVERTIME_FEE { get; set; }
        public int MECHANIC_JANITOR_OVERTIME_FEE { get; set; }
        public int CONSCRIPTION_OVERTIME_FEE { get; set; }
        public int UN_REST_OVERTIME_FEE { get; set; }
        public int HOLIDAY_SUBSIDY { get; set; }
        public int DOMESTIC_ERRAND_FEE { get; set; }
        public int SHUTTLE_FARE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
