//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_EMatStock
    {
        public string MAT_CODE { get; set; }
        public string MAT_NAME { get; set; }
        public string MAT_APPLY_TYPE_CD { get; set; }
        public string MAT_APPLY_TYPE_NM { get; set; }
        public string MAT_TYPE_CD { get; set; }
        public string MAT_TYPE_NM { get; set; }
        public string MAT_UNIT { get; set; }
        public int MAT_STOCK_AMT { get; set; }
        public int MAT_SAFETY_STOCK_AMT { get; set; }
        public int MAT_LIMIT_AMT { get; set; }
        public int MAT_LIMIT_YEAR { get; set; }
        public int MAT_LIMIT_MON { get; set; }
        public int MAT_LIMIT_DAY { get; set; }
        public string MAT_LIMIT_ROLE_CD { get; set; }
        public string MAT_LIMIT_ROLE_NM { get; set; }
        public string DEL_FLAG { get; set; }
        public string ADD_EMP_CODE { get; set; }
        public string ADD_DT_TM { get; set; }
        public string UPD_EMP_CODE { get; set; }
        public string UPD_DT_TM { get; set; }
    }
}
