//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_EMatApplyForm
    {
        public string EFORMSN { get; set; }
        public string SERIAL_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string ID_NO { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string STAFF_TYPE { get; set; }
        public string RCV_EMP_CODE { get; set; }
        public string RCV_EMP_NAME { get; set; }
        public string RCV_ID_NO { get; set; }
        public string RCV_DEPT_CODE { get; set; }
        public string RCV_DEPT_NAME { get; set; }
        public string RCV_TITLE_CODE { get; set; }
        public string RCV_TITLE_NAME { get; set; }
        public string MAT_APPLY_TYPE_CD { get; set; }
        public string MAT_APPLY_TYPE_NM { get; set; }
        public string MAT_TYPE_CD { get; set; }
        public string OVER_APPLY_AMT_RSN { get; set; }
        public string CANCEL_RSN { get; set; }
        public string MISSION_DEPT { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string RCV_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string YN_HR_DEPT_1 { get; set; }
        public string YN_HR_DEPT_2 { get; set; }
        public string OVER_FLAG { get; set; }
        public string DEL_FLAG { get; set; }
        public string UPD_EMP_CODE { get; set; }
        public string UPD_DT_TM { get; set; }
    }
}
