//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ATravelSubsidy
    {
        public string DEPT_CODE { get; set; }
        public string STAFF_TYPE { get; set; }
        public string START_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_DATE { get; set; }
        public string END_TIME { get; set; }
        public Nullable<int> SUBSIDY_AMOUNT { get; set; }
        public Nullable<decimal> SUBSIDY_DAYS { get; set; }
        public string EMP_CODE { get; set; }
        public string SUBSIDY_YEAR { get; set; }
        public int APPLY_TMS { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public string RELEASE_YEAR_MONTH { get; set; }
        public Nullable<decimal> REGULATE_DAYS { get; set; }
    }
}
