//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFBankDataM
    {
        public int SUBSIDY_TYPE_CODE { get; set; }
        public string SUBSIDY_TYPE_NAME { get; set; }
        public int SUBSIDY_STAFF_TYPE { get; set; }
        public string SUBSIDY_STAFF_TYPENAME { get; set; }
        public int SUBSIDY_STAFF_TYPEDTL { get; set; }
        public string SUBSIDY_STAFF_TYPEDTLNAME { get; set; }
        public string COND_PERD_1 { get; set; }
        public string COND_PERD_2 { get; set; }
        public int SCHOOL_YEAR { get; set; }
        public int SEMESTER { get; set; }
        public int Budget_YEAR { get; set; }
        public int YN_DEPOSIT { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_FULL_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string BANK_ACCOUNT { get; set; }
        public decimal APPLY_AMOUNT { get; set; }
        public string EMAIL { get; set; }
        public string MEDIAFILE_CREATE_DATE { get; set; }
        public string DATA_CREATE_DATE { get; set; }
        public string SUBSIDY_SEND_EMAIL_DATE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
