//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AUnRestOTPayForm
    {
        public string EFORMSN { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string REPORT_GROUP { get; set; }
        public int TOTAL_UN_REST_OVERTIME_FEE { get; set; }
        public int TOTAL_HOLIDAY_SUBSIDY { get; set; }
        public int TOTAL_SHOULD_RECEIVE_AMOUNT { get; set; }
        public int Budget_YEAR { get; set; }
        public string BudgetNo { get; set; }
        public string BudgetName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string SubprojectNo { get; set; }
        public string SubprojectName { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectName { get; set; }
        public int Budget_YEAR2 { get; set; }
        public string BudgetNo2 { get; set; }
        public string BudgetName2 { get; set; }
        public string AccountNo2 { get; set; }
        public string AccountName2 { get; set; }
        public string SubprojectNo2 { get; set; }
        public string SubprojectName2 { get; set; }
        public string ObjectNo2 { get; set; }
        public string ObjectName2 { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string DATA_SOURCE { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string CHIEF_SUID { get; set; }
        public string DIRECTOR_SUID { get; set; }
        public string CASHIER_SUID { get; set; }
        public string CASHIER_DIRECTOR_SUID { get; set; }
        public string ACC_AUDITOR_SUID { get; set; }
        public string ACC_DIRECTOR_SUID { get; set; }
        public string ORG_REPR_SUID { get; set; }
    }
}
