//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DBatch
    {
        public string PAY_CODE { get; set; }
        public string BATCH_NO { get; set; }
        public string PAY_DATE { get; set; }
        public string update_staff { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
