//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVBankDataM
    {
        public int OVERTIME_TYPE_CODE { get; set; }
        public string OVERTIME_TYPE_NAME { get; set; }
        public int OVERTIME_FEE_STAFF_TYPE { get; set; }
        public string OVERTIME_FEE_STAFF_TYPENAME { get; set; }
        public int OVERTIME_FEE_STAFF_TYPEDTL { get; set; }
        public string OVERTIME_FEE_STAFF_TYPEDTLNAME { get; set; }
        public int YN_DEPOSIT { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public int BATCH { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_FULL_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string BANK_ACCOUNT { get; set; }
        public int PAYABLE_TAMOUNT { get; set; }
        public string EMAIL { get; set; }
        public string DATA_CREATE_DATE { get; set; }
        public string MEDIAFILE_CREATE_DATE { get; set; }
        public string OVERTIME_SEND_EMAIL_DATE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
