//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AOvertimeAssignForm
    {
        public string EFORMSN { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string STAFF_TYPE { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string START_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_DATE { get; set; }
        public string END_TIME { get; set; }
        public int APPLY_OVERTIME_HOURS { get; set; }
        public int ZS_DAY_HOURS { get; set; }
        public int ZS_MONTH_HOURS { get; set; }
        public int ZS_MONTH_GENE_HOURS { get; set; }
        public int ZS_MONTH_PROJECT_HOURS { get; set; }
        public string EVENT { get; set; }
        public string ASTAT_APPLY_REASON { get; set; }
        public int ZS_DAY_OVERTIME_TMS { get; set; }
        public string OVERTIME_TYPE { get; set; }
        public string REASON { get; set; }
        public string APPLY_MODE { get; set; }
        public int OVERTIME_DUTYOFF_HOURS { get; set; }
        public int OVERTIME_FEE_HOURS { get; set; }
        public int OVERTIME_FEE_1_HOURS { get; set; }
        public int OVERTIME_FEE_133_HOURS { get; set; }
        public int OVERTIME_FEE_166_HOURS { get; set; }
        public int HOUR_SALARY { get; set; }
        public int OVERTIME_FEE { get; set; }
        public string YN_BRUSH_OVERTIME_MORNING { get; set; }
        public string YN_OVERTIME_NOON { get; set; }
        public string YN_OVERTIME_NIGHT { get; set; }
        public string YN_FT_APPLY_OVERTIME_FEE { get; set; }
        public string YN_DUTYOFF_CANCEL { get; set; }
        public string YN_SD_APPLY_FEE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string YN_HR_DEPT_1 { get; set; }
        public string YN_HR_DEPT_2 { get; set; }
        public string LOCATION { get; set; }
        public string CalOvertimeFeeDT { get; set; }
    }
}
