//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFGBAGK
    {
        public int SUBSIDY_TYPE_CODE { get; set; }
        public string SUBSIDY_TYPE_NAME { get; set; }
        public int SUBSIDY_STAFF_TYPE { get; set; }
        public string SUBSIDY_STAFF_TYPENAME { get; set; }
        public string COND_PERD_1 { get; set; }
        public string COND_PERD_2 { get; set; }
        public int fiscalyear { get; set; }
        public string accounttype { get; set; }
        public decimal importrecno { get; set; }
        public int recno { get; set; }
        public string customeruniversalno { get; set; }
        public string customername { get; set; }
        public string bankaccount { get; set; }
        public string bankaccountname { get; set; }
        public string bankno { get; set; }
        public string bankname { get; set; }
        public decimal checkamt { get; set; }
        public string checkremark { get; set; }
        public string receipttype { get; set; }
        public string remarktext { get; set; }
        public string address { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
