//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVGBAGJ
    {
        public int OVERTIME_TYPE_CODE { get; set; }
        public string OVERTIME_TYPE_NAME { get; set; }
        public int OVERTIME_FEE_STAFF_TYPE { get; set; }
        public string OVERTIME_FEE_STAFF_TYPENAME { get; set; }
        public int OVERTIME_FEE_STAFF_TYPEDTL { get; set; }
        public string OVERTIME_FEE_STAFF_TYPEDTLNAME { get; set; }
        public string COND_PERD_1 { get; set; }
        public string COND_PERD_2 { get; set; }
        public int BATCH { get; set; }
        public int fiscalyear { get; set; }
        public string accounttype { get; set; }
        public decimal importrecno { get; set; }
        public string takemethod { get; set; }
        public string voucherusetype { get; set; }
        public string payremark { get; set; }
        public string windowname { get; set; }
        public string windowtel { get; set; }
        public string windowmail { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
