//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DCashIn
    {
        public int CHECK_DATE { get; set; }
        public string CHECK_NO { get; set; }
        public string CHECK_TITLE { get; set; }
        public int CHECK_AMOUNT { get; set; }
        public string CHECK_TYPE { get; set; }
        public Nullable<int> CHK_DATE { get; set; }
        public string REMARK { get; set; }
        public string PAYINFO { get; set; }
        public string YM { get; set; }
    }
}
