//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CProperty_New
    {
        public string P_Distin { get; set; }
        public string P_SNO { get; set; }
        public string P_NAME { get; set; }
        public string P_ONAME { get; set; }
        public string P_SOURCE { get; set; }
        public string BUY_DATE { get; set; }
        public string GET_DATE { get; set; }
        public string KEEP_DEPT_CODE { get; set; }
        public string KEEP_DEPT_NAME { get; set; }
        public string KEEPER_CODE { get; set; }
        public string KEEPER_NAME { get; set; }
        public string USE_DEPT_CODE { get; set; }
        public string USE_DEPT_NAME { get; set; }
        public string P_USER_CODE { get; set; }
        public string P_USER_NAME { get; set; }
        public string SET_DEPT_CODE { get; set; }
        public string SET_DEPT_NAME { get; set; }
        public Nullable<decimal> P_COUNT_OR_AREA { get; set; }
        public Nullable<decimal> P_COST { get; set; }
        public Nullable<decimal> P_ORG_COST { get; set; }
        public Nullable<decimal> P_DEPRECIATION { get; set; }
        public Nullable<decimal> P_NOW_VALUE { get; set; }
        public string P_CAN_YEARS { get; set; }
        public string P_USED_YM { get; set; }
        public string P_APPLY_YEARS { get; set; }
        public string END_DATE_YN { get; set; }
        public string DAMAGE_YN { get; set; }
        public string P_CANT_UES_DATE { get; set; }
        public string P_TYPE { get; set; }
        public string P_BRAND { get; set; }
        public string CITY_NAME { get; set; }
        public string DISTRICTION_NAME { get; set; }
        public string SECTION_NAME { get; set; }
        public string LAND_NO { get; set; }
        public string BUILD_NO { get; set; }
        public string P_USED_DIST { get; set; }
        public string P_USED_TYPE { get; set; }
        public Nullable<decimal> P_ACREAGE { get; set; }
        public string P_RIGHT_DATE { get; set; }
        public Nullable<decimal> P_RIGHT_ACREAGE { get; set; }
        public string LAND_PRICE_DATE { get; set; }
        public Nullable<decimal> LAND_UNIT_PRICE { get; set; }
        public Nullable<decimal> LADN_TOTAL_PRICE { get; set; }
    }
}
