//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CCA05S
    {
        public string A0501 { get; set; }
        public string A0502 { get; set; }
        public string A0503 { get; set; }
        public string A0504 { get; set; }
        public string A0505 { get; set; }
        public string B0101 { get; set; }
        public string B0102 { get; set; }
        public Nullable<int> B3800 { get; set; }
        public string Comm { get; set; }
        public string A0600 { get; set; }
        public string A0700 { get; set; }
        public string A0800 { get; set; }
        public string UM { get; set; }
        public string MadEOF { get; set; }
        public string Remark { get; set; }
    }
}
