//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFEduBorrowM
    {
        public int SCHOOL_YEAR { get; set; }
        public int SEMESTER { get; set; }
        public string ID_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EFORMSN { get; set; }
        public string FORM_STATUS { get; set; }
        public string DEPT_GROUP_CODE { get; set; }
        public string DEPT_GROUP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public int POSITION_GRADE { get; set; }
        public string SALARY_TYPE { get; set; }
        public int SALARY_GRADE { get; set; }
        public int SALARY_POINT { get; set; }
        public string APPLY_SN { get; set; }
        public string APPLY_DATE { get; set; }
        public int APPLY_TAMOUNT { get; set; }
        public int APPLY_CHILDREN_NUM { get; set; }
        public int SUBSIDY_STAFF_TYPE { get; set; }
        public string SUBSIDY_STAFF_TYPENAME { get; set; }
        public int SUBSIDY_STAFF_TYPEDTL { get; set; }
        public string SUBSIDY_STAFF_TYPEDTLNAME { get; set; }
        public int YN_ALREADY_READ { get; set; }
        public string APPR_DATE { get; set; }
        public string REPORT_PRINT_DATE { get; set; }
        public string FORM_CREATE_DATE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string YN_HR_DEPT_1 { get; set; }
        public string YN_HR_DEPT_2 { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
