//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ABatchDayOffFormDetail
    {
        public string EFORMSN { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string TITLE_NAME { get; set; }
        public string AGENT_CODE { get; set; }
        public string AGENT_NAME { get; set; }
        public string YN_CANCEL_DUTY { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string STAFF_TYPE { get; set; }
    
        public virtual DT311_ABatchDayOffForm DT311_ABatchDayOffForm { get; set; }
    }
}
