//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ACalendar
    {
        public string C_DATE { get; set; }
        public string C_WEEK { get; set; }
        public string ON_DUTY_TYPE { get; set; }
        public string C_REMARK { get; set; }
        public string BrushEmail { get; set; }
        public string C_START_TIME { get; set; }
        public string C_END_TIME { get; set; }
    }
}
