//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CCarMaintenance
    {
        public int FIX_ID { get; set; }
        public string FIX_DATE { get; set; }
        public string FIX_EMP_CODE { get; set; }
        public string CAR_NO { get; set; }
        public string FIX_ITEM { get; set; }
        public int FIX_QTY { get; set; }
        public int UNIT_PRICE { get; set; }
        public string UNIT { get; set; }
        public string FEE_TYPE { get; set; }
        public string FIX_FACTORY { get; set; }
        public string UPDATE_STAFF { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
