//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AErrandFeeForm
    {
        public string EFORMSN { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string STAFF_TYPE { get; set; }
        public string ERRAND_STAFF_TYPE { get; set; }
        public string SALARY_GRADE_NAME { get; set; }
        public string ERRAND_EFORMSN { get; set; }
        public string EVENT { get; set; }
        public string ERRAND_PLACE { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public Nullable<decimal> TOTAL_DAY_HOURS { get; set; }
        public Nullable<int> ERRAND_TOTAL_FEE { get; set; }
        public string ERRAND_REMARK { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string YN_HR_DEPT_1 { get; set; }
        public string YN_HR_DEPT_2 { get; set; }
        public string FLOWSN { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string AGENT_SUID { get; set; }
        public string CHIEF_SUID { get; set; }
        public string DIRECTOR_SUID { get; set; }
        public string ATT_MANAGER_SUID { get; set; }
        public string ATT_DIRECTOR_SUID { get; set; }
        public string ACC_AUDITOR_SUID { get; set; }
        public string ACC_DIRECTOR_SUID { get; set; }
        public string ORG_REPR_SUID { get; set; }
        public string TX_ERRAND_YEAR_1 { get; set; }
        public string TX_ERRAND_MONTH_1 { get; set; }
        public string TX_ERRAND_DAY_1 { get; set; }
        public string TX_START_END_PLACE_1 { get; set; }
        public string TX_TASK_DSCPT_1 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_1 { get; set; }
        public Nullable<int> TX_CAR_FEE_1 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_1 { get; set; }
        public Nullable<int> TX_SHIP_FEE_1 { get; set; }
        public Nullable<int> TX_LODGING_FEE_1 { get; set; }
        public Nullable<int> TX_MEAL_FEE_1 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_1 { get; set; }
        public string TX_ERRAND_YEAR_2 { get; set; }
        public string TX_ERRAND_MONTH_2 { get; set; }
        public string TX_ERRAND_DAY_2 { get; set; }
        public string TX_START_END_PLACE_2 { get; set; }
        public string TX_TASK_DSCPT_2 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_2 { get; set; }
        public Nullable<int> TX_CAR_FEE_2 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_2 { get; set; }
        public Nullable<int> TX_SHIP_FEE_2 { get; set; }
        public Nullable<int> TX_LODGING_FEE_2 { get; set; }
        public Nullable<int> TX_MEAL_FEE_2 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_2 { get; set; }
        public string TX_ERRAND_YEAR_3 { get; set; }
        public string TX_ERRAND_MONTH_3 { get; set; }
        public string TX_ERRAND_DAY_3 { get; set; }
        public string TX_START_END_PLACE_3 { get; set; }
        public string TX_TASK_DSCPT_3 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_3 { get; set; }
        public Nullable<int> TX_CAR_FEE_3 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_3 { get; set; }
        public Nullable<int> TX_SHIP_FEE_3 { get; set; }
        public Nullable<int> TX_LODGING_FEE_3 { get; set; }
        public Nullable<int> TX_MEAL_FEE_3 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_3 { get; set; }
        public string TX_ERRAND_YEAR_4 { get; set; }
        public string TX_ERRAND_MONTH_4 { get; set; }
        public string TX_ERRAND_DAY_4 { get; set; }
        public string TX_START_END_PLACE_4 { get; set; }
        public string TX_TASK_DSCPT_4 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_4 { get; set; }
        public Nullable<int> TX_CAR_FEE_4 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_4 { get; set; }
        public Nullable<int> TX_SHIP_FEE_4 { get; set; }
        public Nullable<int> TX_LODGING_FEE_4 { get; set; }
        public Nullable<int> TX_MEAL_FEE_4 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_4 { get; set; }
        public string TX_ERRAND_YEAR_5 { get; set; }
        public string TX_ERRAND_MONTH_5 { get; set; }
        public string TX_ERRAND_DAY_5 { get; set; }
        public string TX_START_END_PLACE_5 { get; set; }
        public string TX_TASK_DSCPT_5 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_5 { get; set; }
        public Nullable<int> TX_CAR_FEE_5 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_5 { get; set; }
        public Nullable<int> TX_SHIP_FEE_5 { get; set; }
        public Nullable<int> TX_LODGING_FEE_5 { get; set; }
        public Nullable<int> TX_MEAL_FEE_5 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_5 { get; set; }
        public string TX_ERRAND_YEAR_6 { get; set; }
        public string TX_ERRAND_MONTH_6 { get; set; }
        public string TX_ERRAND_DAY_6 { get; set; }
        public string TX_START_END_PLACE_6 { get; set; }
        public string TX_TASK_DSCPT_6 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_6 { get; set; }
        public Nullable<int> TX_CAR_FEE_6 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_6 { get; set; }
        public Nullable<int> TX_SHIP_FEE_6 { get; set; }
        public Nullable<int> TX_LODGING_FEE_6 { get; set; }
        public Nullable<int> TX_MEAL_FEE_6 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_6 { get; set; }
        public string TX_ERRAND_YEAR_7 { get; set; }
        public string TX_ERRAND_MONTH_7 { get; set; }
        public string TX_ERRAND_DAY_7 { get; set; }
        public string TX_START_END_PLACE_7 { get; set; }
        public string TX_TASK_DSCPT_7 { get; set; }
        public Nullable<int> TX_AIRPLANE_FEE_7 { get; set; }
        public Nullable<int> TX_CAR_FEE_7 { get; set; }
        public Nullable<int> TX_TRAIN_FEE_7 { get; set; }
        public Nullable<int> TX_SHIP_FEE_7 { get; set; }
        public Nullable<int> TX_LODGING_FEE_7 { get; set; }
        public Nullable<int> TX_MEAL_FEE_7 { get; set; }
        public Nullable<int> TX_RECEIPTS_QTY_7 { get; set; }
        public Nullable<int> Errand_Receipt_QTY { get; set; }
    }
}
