//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CRoomInfo
    {
        public int CONFERENCE_ROOM_CODE { get; set; }
        public string CONFERENCE_ROOM_NAME { get; set; }
        public string CONFERENCE_ROOM_LOCATION { get; set; }
        public int MAX_CONTENT_NO { get; set; }
        public string CONFERENCE_ROOM_DEPT_CODE { get; set; }
        public string CONFERENCE_ROOM_MGR_CODE { get; set; }
        public string REMARK { get; set; }
        public string CONFERENCE_ROOM_MGR_TEL { get; set; }
        public string SEALED_START_DATE { get; set; }
        public string SEALED_END_DATE { get; set; }
        public string SEALED_REASON { get; set; }
        public string PROJECTOR { get; set; }
        public string RECORDER { get; set; }
        public string MICROPHONE { get; set; }
        public string LASERPEN { get; set; }
        public string OTHER_EQUIPMENT { get; set; }
        public string UPDATE_STAFF { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string DELETE_FLAG { get; set; }
        public string CLOSETIME_START_MON { get; set; }
        public string CLOSETIME_END_MON { get; set; }
        public string CLOSETIME_START_TUE { get; set; }
        public string CLOSETIME_END_TUE { get; set; }
        public string CLOSETIME_START_WED { get; set; }
        public string CLOSETIME_END_WED { get; set; }
        public string CLOSETIME_START_THU { get; set; }
        public string CLOSETIME_END_THU { get; set; }
        public string CLOSETIME_START_FRI { get; set; }
        public string CLOSETIME_END_FRI { get; set; }
        public string CLOSETIME_START_SAT { get; set; }
        public string CLOSETIME_END_SAT { get; set; }
        public string CLOSETIME_START_SUN { get; set; }
        public string CLOSETIME_END_SUN { get; set; }
    }
}
