//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ATempReportData1
    {
        public string DEPT_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public string VAC_TYPE { get; set; }
        public string DAYOFF_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public int TOTAL_HOURS { get; set; }
        public string APPLY_DATE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string SEND_STATUS { get; set; }
        public string ERRAND_PLACE { get; set; }
        public string ERRAND_EVENT { get; set; }
        public string DAYOFF_TYPE { get; set; }
        public string ORG_EFORMSN { get; set; }
        public string ORG_FORM_TYPE { get; set; }
        public string SEQ_DAYOFF_SN { get; set; }
        public string Report_Uid { get; set; }
    }
}
