//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DT311_ACode
    {
        [DisplayName("代碼類別")]
        [StringLength(1)]
        public string CODE_TYPE { get; set; }

        [DisplayName("代碼")]
        [Required(ErrorMessage = "代碼不能為空")]
        public string CODE { get; set; }

        [DisplayName("代碼名稱")]
        [Required(ErrorMessage = "代碼名稱不能為空")]
        public string CODE_NAME { get; set; }

        [DisplayName("順序")]
        [Range(1,99)]
        [RegularExpression(@"^[1-9]d*$", ErrorMessage = "請輸入正整數")]
        public Nullable<int> CODE_SEQ { get; set; }
    }
}
