//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DCPAUploadFileD
    {
        public int FEE_TYPE_CODE { get; set; }
        public string FEE_TYPE_NAME { get; set; }
        public string COND_PERD_1 { get; set; }
        public string COND_PERD_2 { get; set; }
        public int COND_PERD_3 { get; set; }
        public string SEND_DATA_ORG_CODE { get; set; }
        public string DATA_YM { get; set; }
        public string SALARY_LIST_TYPE_CODE { get; set; }
        public string ID_NO_AFT_5 { get; set; }
        public string DEL_MARK { get; set; }
        public string ID_NO_1 { get; set; }
        public int WITHDRAW_AMT { get; set; }
        public string SALARY_LIST_TYPE { get; set; }
        public decimal DAYS { get; set; }
        public string CLASS_TYPE { get; set; }
        public string KINSFOLK { get; set; }
        public string FUNDS_TYPE { get; set; }
        public string ID_NO_2_5 { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
