//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AEmployee_1040914
    {
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string HADDR { get; set; }
        public string BORN_DATE { get; set; }
        public string ONBOARD_DATE { get; set; }
        public string QUIT_DATE { get; set; }
        public string QUIT_REASON { get; set; }
        public string EMAIL { get; set; }
        public string STAFF_TYPE { get; set; }
        public string BRUSH_GROUP { get; set; }
        public string ATT_GROUP { get; set; }
        public string TEMP_CARD_CODE { get; set; }
        public string YN_BRUSH_DUTY { get; set; }
        public string YN_BRUSH_ERRAND_OUT { get; set; }
        public string YN_BRUSH_OVERTIME_MORNING { get; set; }
        public string YN_BRUSH_OVERTIME_NOON { get; set; }
        public string YN_BRUSH_OVERTIME_NIGHT { get; set; }
        public Nullable<int> SENIORITY { get; set; }
        public Nullable<decimal> ZSY_HOLIDAY_DAYS { get; set; }
        public Nullable<decimal> ZSY_PERSON_LEAVE_DAYS { get; set; }
        public Nullable<decimal> ZSY_SICK_LEAVE_DAYS { get; set; }
        public Nullable<decimal> LY_HOLIDAY_RESV_DAYS { get; set; }
        public Nullable<decimal> LY_HOLIDAY_RESV_RESTED { get; set; }
        public Nullable<decimal> BLY_HOLIDAY_RESV_DAYS { get; set; }
        public Nullable<decimal> BLY_HOLIDAY_RESV_RESTED { get; set; }
        public Nullable<decimal> ZSY_HOLIDAY_RESV_DAYS { get; set; }
        public Nullable<decimal> ADVANCE_DAYS { get; set; }
        public Nullable<decimal> REGULATE_DAYS { get; set; }
        public string SCHOOL_DEPT { get; set; }
        public string GRADUATE_YEAR_MONTH { get; set; }
        public string COMU_ADDR { get; set; }
        public string UPDATE_STAFF { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string AGENT1 { get; set; }
        public string AGENT2 { get; set; }
        public string AGENT3 { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string BELONG_DEPT_CODE { get; set; }
        public string ATT_DEPT_CODE { get; set; }
        public string TITLE_CODE { get; set; }
        public string BASE_YEAR { get; set; }
        public string YN_DEPT_MANAGER { get; set; }
        public string STAMP_TITLE_NAME { get; set; }
        public string REPRESENT_TITLE_NAME { get; set; }
        public string REPRESENT_EMP_NAME { get; set; }
        public string REPRESENT_TYPE { get; set; }
        public string LDAP_ROLE { get; set; }
        public string empemail { get; set; }
        public string TX_TRANS_EMP_NAME { get; set; }
        public string TX_FULL_EMP_NAME { get; set; }
        public string OLD_EMP_CODE { get; set; }
        public string YN_OTHER_Manager { get; set; }
        public string OTHER_DEPT_CODE { get; set; }
        public string REMARK { get; set; }
        public string Education { get; set; }
    }
}
