//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DTRProcess
    {
        public string RECEIPT_TYPE { get; set; }
        public string REMIT_BARCODE { get; set; }
        public string RDC_NO { get; set; }
        public Nullable<int> RECEIPT_DATE { get; set; }
        public string RECEIPT_NO { get; set; }
        public Nullable<int> RECEIPT_AMOUNT { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> KEYIN_DATE { get; set; }
    }
}
