//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AShortDistFareForm
    {
        public string EFORMSN { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string STAFF_TYPE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string ERRAND_OUT_EFORMSN { get; set; }
        public string START_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_DATE { get; set; }
        public string END_TIME { get; set; }
        public Nullable<decimal> TOTAL_DAY_HOURS { get; set; }
        public string EVENT { get; set; }
        public string ERRAND_PLACE { get; set; }
        public Nullable<int> TOTAL_FARE { get; set; }
        public string UNABLE_GET_REASON { get; set; }
        public string FORM_REMARK { get; set; }
        public string VOUCH_NO { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string YN_APPLY_ERRAND_OUT { get; set; }
        public string NO_ERRAND_OUT_TYPE { get; set; }
        public string NO_ERRAND_OUT_REASON { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public Nullable<int> Budget_YEAR { get; set; }
        public string BudgetNo { get; set; }
        public string BudgetName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string SubprojectNo { get; set; }
        public string SubprojectName { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectName { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string CHIEF_SUID { get; set; }
        public string DIRECTOR_SUID { get; set; }
        public string ACC_AUDITOR_SUID { get; set; }
        public string ACC_DIRECTOR_SUID { get; set; }
        public string ORG_REPR_SUID { get; set; }
        public string TX_GO_PLACE_1 { get; set; }
        public string TX_RETURN_PLACE_1 { get; set; }
        public string TX_GO_PLACE_2 { get; set; }
        public string TX_RETURN_PLACE_2 { get; set; }
    }
}
