//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AOvertimeHourAcu
    {
        public string EMP_CODE { get; set; }
        public string YEAR_MONTH { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<int> GENE_OVERTIME_HOUR_ACU { get; set; }
        public Nullable<int> PROJECT_OVERTIME_HOUR_ACU { get; set; }
    }
}
