//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT313_ZBJCRecord
    {
        public string BJC_CODE { get; set; }
        public int BJC_SUCCESS { get; set; }
        public int BJC_FAIL { get; set; }
        public System.DateTime BJC_EXECUTE_DT { get; set; }
    }
}
