//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFMarryBornDieD
    {
        public string ID_NO { get; set; }
        public string EMP_CODE { get; set; }
        public int APPLY_TYPE { get; set; }
        public int SUBSIDY_TYPE_CODE { get; set; }
        public string FACT_HAPPEN_DATE { get; set; }
        public string EFORMSN { get; set; }
        public string RELATIVE_ID_NO { get; set; }
        public string RELATIVE_NAME { get; set; }
        public int FAMILY_TYPE { get; set; }
        public string FAMILY_TYPE_OTHER { get; set; }
        public int FAMILY_CURRENT_LIVE_ADDR { get; set; }
        public int MMSALARY_AMT { get; set; }
        public int SUBSIDY { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
