//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace testMVC.Models
{
    using System;

    public partial class DT311_ACode
    {
        [Key]
        public string CODE_TYPE { get; set; }
        [Key]
        public string CODE { get; set; }
        [Required]
        public string CODE_NAME { get; set; }
        [Required]
        public Nullable<int> CODE_SEQ { get; set; }
    }
}
