//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFEduBorrowD
    {
        public int SCHOOL_YEAR { get; set; }
        public int SEMESTER { get; set; }
        public string ID_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string EFORMSN { get; set; }
        public string CHILDREN_NAME { get; set; }
        public string CHILDREN_ID_NO { get; set; }
        public string SCHOOL_NAME { get; set; }
        public int GRADETYPE { get; set; }
        public int GRADE { get; set; }
        public int SCHOOL_TYPE_CODE { get; set; }
        public string SCHOOL_TYPE_NAME { get; set; }
        public int PUB_PRI_TYPE_CODE { get; set; }
        public string PUB_PRI_TYPE_NAME { get; set; }
        public int APPLY_SUBSIDY { get; set; }
        public string REMARK { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
