//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CGETCARFORM_D
    {
        public string EFORMSN { get; set; }
        public string CAR_NO { get; set; }
        public string DRIVER_EMP_CODE { get; set; }
        public Nullable<int> MILEAGE { get; set; }
        public Nullable<int> USED_OIL_QTY { get; set; }
    }
}
