//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFEduCBorrowRptM
    {
        public int SCHOOL_YEAR { get; set; }
        public int SEMESTER { get; set; }
        public string TABULATION_DEPT_CODE { get; set; }
        public string TABULATION_DEPT_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string EFORMSN { get; set; }
        public string FORM_STATUS { get; set; }
        public string ID_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public int YN_END { get; set; }
        public string YN_END_MARK { get; set; }
        public int Budget_YEAR { get; set; }
        public string BudgetNo { get; set; }
        public string BudgetName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string DeducAccountNo { get; set; }
        public string DeducAccountName { get; set; }
        public string SubprojectNo { get; set; }
        public string SubprojectName { get; set; }
        public string ObjectNo_1 { get; set; }
        public string ObjectName_1 { get; set; }
        public string ObjectNo_2 { get; set; }
        public string ObjectName_2 { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectName { get; set; }
        public string DeducObjectNo { get; set; }
        public string DeducObjectName { get; set; }
        public int DETAILLIST_CANCELED_TAMOUNT { get; set; }
        public int DETAILLIST_RETRIEVE_TAMOUNT { get; set; }
        public string DETAILLIST_CREATE_DATE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string REPORT_PRINT_DATE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string UPLOAD_EXPORT_MARK_GENEPERSON { get; set; }
        public string UPLOAD_EXPORT_MARK_NOGENEPERSON { get; set; }
        public string UPLOAD_EXPORT_MARK_NOGENEORG { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string DIRECTOR_SUID { get; set; }
        public string HR_MANAGER_SUID { get; set; }
        public string HR_DIRECTOR_SUID { get; set; }
        public string ACC_AUDITOR_SUID { get; set; }
        public string ACC_DIRECTOR_SUID { get; set; }
        public string ORG_REPR_SUID { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
