//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DTRMain
    {
        public int TRCV_DATE { get; set; }
        public string TRCV_TYPE { get; set; }
        public string REMIT_BARCODE { get; set; }
        public string RDC_NO { get; set; }
        public string REMIT_NO { get; set; }
        public string REMIT_NAME { get; set; }
        public Nullable<int> REMIT_AMOUNT { get; set; }
        public Nullable<int> RECEIPT_AMOUNT { get; set; }
        public Nullable<int> VOUCHER_AMOUNT { get; set; }
        public string REMARK { get; set; }
        public string BALANCE_STATUS { get; set; }
        public string BUSI_TYPE { get; set; }
        public string RDC_NO_BARCODE { get; set; }
        public Nullable<int> KEYIN_DATE { get; set; }
        public Nullable<int> BALANCE_DATE { get; set; }
        public Nullable<int> FT_PAY_DAY { get; set; }
        public string Remit_Group_Code { get; set; }
    }
}
