//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AAttDataStl
    {
        public string STL_YEAR { get; set; }
        public Nullable<System.DateTime> STL_DATE { get; set; }
        public string STL_STAFF { get; set; }
        public string STAFF_TYPE { get; set; }
    }
}
