//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVReportMain2
    {
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public int BATCH { get; set; }
        public int OVERTIME_FEE_STAFF_TYPE { get; set; }
        public string DEPT_GROUP_CODE { get; set; }
        public string EFORMSN { get; set; }
        public string DEPT_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public string OVERTIME_DATE { get; set; }
        public string OVERTIME_START_TIME { get; set; }
        public string OVERTIME_END_TIME { get; set; }
        public Nullable<int> ABLE_OFF_HOURS { get; set; }
        public Nullable<int> OVERTIME_FEE_HOURS { get; set; }
        public Nullable<int> HOURS_SALARY { get; set; }
        public Nullable<int> STOT { get; set; }
        public string EVENT { get; set; }
        public string OVERTIME_KIND { get; set; }
        public string REMARK { get; set; }
        public string ORG_APPLY_EFORMSN { get; set; }
        public string FORM_CREATE_DATE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
