//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ABrushRecord
    {
        public string EMP_CODE { get; set; }
        public string BRUSH_DATE { get; set; }
        public string MORNING_ON_DUTY { get; set; }
        public string NOON_ON_DUTY { get; set; }
        public string OFF_DUTY { get; set; }
        public string FT_OVERTIME_START { get; set; }
        public string FT_OVERTIME_END { get; set; }
        public string SD_OVERTIME_START { get; set; }
        public string SD_OVERTIME_END { get; set; }
        public string TRD_OVERTIME_START { get; set; }
        public string TRD_OVERTIME_END { get; set; }
        public string FT_ERRAND_OUT_LEAVE { get; set; }
        public string SD_ERRAND_OUT_LEAVE { get; set; }
        public string CANCEL_MARK { get; set; }
        public string FT_ERRAND_OUT_RTN { get; set; }
        public string SD_ERRAND_OUT_RTN { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_STAFF { get; set; }
    }
}
