//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ADayOffForm
    {
        public string EFORMSN { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string STAFF_TYPE { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string DAYOFF_TYPE { get; set; }
        public string ABROAD_TYPE { get; set; }
        public string NOW_TASK { get; set; }
        public string GO_AREA { get; set; }
        public string VAC_TYPE { get; set; }
        public string VAC_TYPE_NAME { get; set; }
        public string START_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_DATE { get; set; }
        public string END_TIME { get; set; }
        public Nullable<decimal> TOTAL_DAY_HOURS { get; set; }
        public string YN_INCLUDE_HOLIDAY { get; set; }
        public string EVENT { get; set; }
        public string ERRAND_PLACE { get; set; }
        public string AGENT_CODE { get; set; }
        public string YN_CANCEL_DUTY { get; set; }
        public string YN_ERRAND_OUT_FORM { get; set; }
        public Nullable<decimal> MRG_DAY_HOURS { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string YN_HR_DEPT_1 { get; set; }
        public string YN_HR_DEPT_2 { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string AGENT_SUID { get; set; }
        public string CHIEF_SUID { get; set; }
        public string DIRECTOR_SUID { get; set; }
        public string ORG_REPR_SUID { get; set; }
    
        public virtual DT311_AAbortionOffDetail DT311_AAbortionOffDetail { get; set; }
        public virtual DT311_AAMCMaternityOffDetail DT311_AAMCMaternityOffDetail { get; set; }
    }
}
