//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AAttStat
    {
        public string STAT_YEAR { get; set; }
        public string STAT_MONTH { get; set; }
        public string EMP_CODE { get; set; }
        public int PERSON_LEAVE_HOURS { get; set; }
        public int SICK_LEAVE_HOURS { get; set; }
        public int HOLIDAY_HOURS { get; set; }
        public int WEDDING_OFF_HOURS { get; set; }
        public int FUNERAL_OFF_HOURS { get; set; }
        public int LABOR_OFF_HOURS { get; set; }
        public int ABORTION_OFF_HOURS { get; set; }
        public int ROUTE_OFF_HOURS { get; set; }
        public int ABSENT_HOURS { get; set; }
        public int MATERNITY_LEAVE_HOURS { get; set; }
        public int ACM_MATERNITY_LEAVE_HOURS { get; set; }
        public int MARROW_DONATE_HOLIDAY_HOURS { get; set; }
        public int ERRAND_OUT_HOURS { get; set; }
        public int ERRAND_HOLIDAY_HOURS { get; set; }
        public int ERRAND_HOURS { get; set; }
        public int ABROAD_HOURS { get; set; }
        public int OVERTIME_DUTYOFF_HOURS { get; set; }
        public int EXT_SICK_LEAVE_HOURS { get; set; }
        public int ERRAND_DUTYOFF_HOURS { get; set; }
        public int HOUSE_MOVING_HOLIDAY_HOURS { get; set; }
        public int OTHER_DUTYOFF_HOURS { get; set; }
        public int DISASTER_HOLIDAY_HOURS { get; set; }
        public int OTHER_HOLIDAY_HOURS { get; set; }
        public int FAMILY_CARE_OFF_HOURS { get; set; }
        public int MENSES_LEAVE_HOURS { get; set; }
    }
}
