//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ABrushGroup
    {
        public string BRUSH_GROUP { get; set; }
        public string BRUSH_GROUP_NAME { get; set; }
        public int WORK_HOUR { get; set; }
        public string STD_ON { get; set; }
        public string STD_OFF { get; set; }
        public string FLEX_ON_START { get; set; }
        public string FLEX_ON_END { get; set; }
        public string FLEX_OFF_START { get; set; }
        public string FLEX_OFF_END { get; set; }
        public string REST_TIME_START { get; set; }
        public string REST_TIME_END { get; set; }
        public string FT_CAN_OVERTIME_START { get; set; }
        public string FT_CAN_OVERTIME_END { get; set; }
        public string SD_CAN_OVERTIME_START { get; set; }
        public string SD_CAN_OVERTIME_END { get; set; }
        public string TRD_CAN_OVERTIME_START { get; set; }
        public string TRD_CAN_OVERTIME_END { get; set; }
    }
}
