//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AUnbrushCertForm
    {
        public string EFORMSN { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string STAFF_TYPE { get; set; }
        public string BRUSH_DATE { get; set; }
        public string HASTE_CONTENT { get; set; }
        public Nullable<int> ALREADY_FORGET_TMS { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string TX_BRUSH_TYPE_1 { get; set; }
        public string TX_BRUSH_TIME_1 { get; set; }
        public string TX_EVENT_TYPE_1 { get; set; }
        public string TX_OTHER_REASON_1 { get; set; }
        public string TX_BRUSH_TYPE_2 { get; set; }
        public string TX_BRUSH_TIME_2 { get; set; }
        public string TX_EVENT_TYPE_2 { get; set; }
        public string TX_OTHER_REASON_2 { get; set; }
        public string TX_BRUSH_TYPE_3 { get; set; }
        public string TX_BRUSH_TIME_3 { get; set; }
        public string TX_EVENT_TYPE_3 { get; set; }
        public string TX_OTHER_REASON_3 { get; set; }
        public string TX_BRUSH_TYPE_4 { get; set; }
        public string TX_BRUSH_TIME_4 { get; set; }
        public string TX_EVENT_TYPE_4 { get; set; }
        public string TX_OTHER_REASON_4 { get; set; }
        public string TX_BRUSH_TYPE_5 { get; set; }
        public string TX_BRUSH_TIME_5 { get; set; }
        public string TX_EVENT_TYPE_5 { get; set; }
        public string TX_OTHER_REASON_5 { get; set; }
        public string TX_BRUSH_TYPE_6 { get; set; }
        public string TX_BRUSH_TIME_6 { get; set; }
        public string TX_EVENT_TYPE_6 { get; set; }
        public string TX_OTHER_REASON_6 { get; set; }
    }
}
