//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DPettyCash
    {
        public int KEYIN_DATE { get; set; }
        public int DAY_SN { get; set; }
        public string NAME { get; set; }
        public string DIGEST { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_CODE { get; set; }
        public string FEE_NAME { get; set; }
        public string FEE_CODE { get; set; }
        public int AMOUNT { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> REPORT_SN { get; set; }
        public string ITEM_YEAR { get; set; }
    }
}
