//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AWaitHandleFieldSetting
    {
        public string FORM_ID { get; set; }
        public int CELL_NO { get; set; }
        public string REPORT_TITLE { get; set; }
        public string HEADER_ALIGN { get; set; }
        public string FIELD_NAME { get; set; }
        public string STYLE_WIDTH { get; set; }
        public string STYLE_TEXT_ALIGN { get; set; }
        public string YN_SUM { get; set; }
        public string FIELD_TYPE { get; set; }
    }
}
