//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DRemitLog
    {
        public int RemitID { get; set; }
        public string RemitDate { get; set; }
        public string RemitAccount { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string ID_NO { get; set; }
        public string RemitTYPE { get; set; }
        public Nullable<decimal> RemitAmount { get; set; }
        public string RemitStatus { get; set; }
        public string RemitRemark { get; set; }
        public string RemitCust { get; set; }
        public decimal ShouldAmount { get; set; }
        public string CompareStatus { get; set; }
        public string SN { get; set; }
        public string ShouldRemitDate { get; set; }
        public string RemitName { get; set; }
        public string OriginTable { get; set; }
        public string OriginKey { get; set; }
    }
}
