//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFEduCBorrowRptD
    {
        public int SCHOOL_YEAR { get; set; }
        public int SEMESTER { get; set; }
        public string TABULATION_DEPT_CODE { get; set; }
        public string EFORMSN { get; set; }
        public string TABULATION_ID_NO { get; set; }
        public string TABULATION_EMP_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_FULL_NAME { get; set; }
        public string ORG_DEPT_CODE { get; set; }
        public string ORG_DEPT_FULL_NAME { get; set; }
        public string ID_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string TITLE_NAME { get; set; }
        public int SUBSIDY_STAFF_TYPE { get; set; }
        public string SUBSIDY_STAFF_TYPENAME { get; set; }
        public int SUBSIDY_STAFF_TYPEDTL { get; set; }
        public string SUBSIDY_STAFF_TYPEDTLNAME { get; set; }
        public string APPLY_SN { get; set; }
        public string APPLY_LOAN_DATE { get; set; }
        public int ORG_APPLY_LOAN_AMOUNT { get; set; }
        public string APPLY_CANCELED_DATE { get; set; }
        public int CANCELED_TAMOUNT { get; set; }
        public int UN_CANCELED_TAMOUNT { get; set; }
        public int APPLY_CHILDREN_NUM { get; set; }
        public int CANCELED_CHILDREN_NUM { get; set; }
        public int UN_CANCELED_CHILDREN_NUM { get; set; }
        public string LOAN_APPLY_SN { get; set; }
        public int COLLEGE_PUBLIC_CHILDREN_NUM { get; set; }
        public int COLLEGE_PRIV_CHILDREN_NUM { get; set; }
        public int COLLEGE_NCLASS_CHILDREN_NUM { get; set; }
        public int COLLEGEAFT_PUBLIC_CHILDREN_NUM { get; set; }
        public int COLLEGEAFT_PRIV_CHILDREN_NUM { get; set; }
        public int COLLEGEAFT_NCLASS_CHILDREN_NUM { get; set; }
        public int COLLEGELP_PUBLIC_CHILDREN_NUM { get; set; }
        public int COLLEGELP_PRIV_CHILDREN_NUM { get; set; }
        public int SENIORHIGH_PUBLIC_CHILDREN_NUM { get; set; }
        public int SENIORHIGH_PRIV_CHILDREN_NUM { get; set; }
        public int VOCATIONAL_PUBLIC_CHILDREN_NUM { get; set; }
        public int VOCATIONAL_PRIV_CHILDREN_NUM { get; set; }
        public int VOCATIONAL_SELFSUFFICIENCY_CHILD { get; set; }
        public int VOCATIONAL_FUNCTIONSKILL_CHILDRE { get; set; }
        public int JUNIORHIGH_CHILDREN_NUM { get; set; }
        public int ELEMENTARY_CHILDREN_NUM { get; set; }
        public string ORG_LOAN_EFORMSN { get; set; }
        public string ORG_CANCELED_EFORMSN { get; set; }
        public string REMARK { get; set; }
        public string UPDATE_STAFF { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
