//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_ACancelDayOffForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DT311_ACancelDayOffForm()
        {
            this.DT311_ACancelDayOffFormDetail = new HashSet<DT311_ACancelDayOffFormDetail>();
        }
    
        public string EFORMSN { get; set; }
        public string EMP_CODE { get; set; }
        public string ID_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WORK_DEPT_CODE { get; set; }
        public string WORK_DEPT_NAME { get; set; }
        public string TITLE_NAME { get; set; }
        public string TITLE_CODE { get; set; }
        public string WRITER_EMP_NAME { get; set; }
        public string WRITER_EMP_CODE { get; set; }
        public string STAFF_TYPE { get; set; }
        public string CHANGE_REASON { get; set; }
        public Nullable<decimal> MRG_DAY_HOURS { get; set; }
        public string DAYOFF_TYPE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPR_DATE { get; set; }
        public string APPLICANT_ROLE_CODE { get; set; }
        public string HANDLER_EMP_NAME { get; set; }
        public string FORM_STATUS { get; set; }
        public string SYSTEMDEATTACHMENT { get; set; }
        public string SYSATTACHMENTSIZE { get; set; }
        public string SYSTEMDEFATTACHUID { get; set; }
        public string SYSTEMDEFIMPORTANT { get; set; }
        public string SYSTEMDEFCOMMENT { get; set; }
        public string FLOWSN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string XFLOW_ROLE_CODE { get; set; }
        public string YN_DIVISION_STAFF { get; set; }
        public string YN_HR_DEPT_1 { get; set; }
        public string YN_HR_DEPT_2 { get; set; }
        public string TX_EVENT { get; set; }
        public string TX_SOURCE_TYPE { get; set; }
        public string TX_START_DATE_1 { get; set; }
        public string TX_END_DATE_1 { get; set; }
        public string TX_START_TIME_1 { get; set; }
        public string TX_END_TIME_1 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_1 { get; set; }
        public string TX_VAC_TYPE_1 { get; set; }
        public string TX_START_DATE_2 { get; set; }
        public string TX_END_DATE_2 { get; set; }
        public string TX_START_TIME_2 { get; set; }
        public string TX_END_TIME_2 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_2 { get; set; }
        public string TX_VAC_TYPE_2 { get; set; }
        public string TX_START_DATE_3 { get; set; }
        public string TX_END_DATE_3 { get; set; }
        public string TX_START_TIME_3 { get; set; }
        public string TX_END_TIME_3 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_3 { get; set; }
        public string TX_VAC_TYPE_3 { get; set; }
        public string TX_START_DATE_4 { get; set; }
        public string TX_END_DATE_4 { get; set; }
        public string TX_START_TIME_4 { get; set; }
        public string TX_END_TIME_4 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_4 { get; set; }
        public string TX_VAC_TYPE_4 { get; set; }
        public string TX_START_DATE_5 { get; set; }
        public string TX_END_DATE_5 { get; set; }
        public string TX_START_TIME_5 { get; set; }
        public string TX_END_TIME_5 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_5 { get; set; }
        public string TX_VAC_TYPE_5 { get; set; }
        public string TX_START_DATE_6 { get; set; }
        public string TX_END_DATE_6 { get; set; }
        public string TX_START_TIME_6 { get; set; }
        public string TX_END_TIME_6 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_6 { get; set; }
        public string TX_VAC_TYPE_6 { get; set; }
        public string TX_START_DATE_7 { get; set; }
        public string TX_END_DATE_7 { get; set; }
        public string TX_START_TIME_7 { get; set; }
        public string TX_END_TIME_7 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_7 { get; set; }
        public string TX_VAC_TYPE_7 { get; set; }
        public string TX_START_DATE_8 { get; set; }
        public string TX_END_DATE_8 { get; set; }
        public string TX_START_TIME_8 { get; set; }
        public string TX_END_TIME_8 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_8 { get; set; }
        public string TX_VAC_TYPE_8 { get; set; }
        public string TX_START_DATE_9 { get; set; }
        public string TX_END_DATE_9 { get; set; }
        public string TX_START_TIME_9 { get; set; }
        public string TX_END_TIME_9 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_9 { get; set; }
        public string TX_VAC_TYPE_9 { get; set; }
        public string TX_START_DATE_10 { get; set; }
        public string TX_END_DATE_10 { get; set; }
        public string TX_START_TIME_10 { get; set; }
        public string TX_END_TIME_10 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_10 { get; set; }
        public string TX_VAC_TYPE_10 { get; set; }
        public string TX_START_DATE_11 { get; set; }
        public string TX_END_DATE_11 { get; set; }
        public string TX_START_TIME_11 { get; set; }
        public string TX_END_TIME_11 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_11 { get; set; }
        public string TX_VAC_TYPE_11 { get; set; }
        public string TX_START_DATE_12 { get; set; }
        public string TX_END_DATE_12 { get; set; }
        public string TX_START_TIME_12 { get; set; }
        public string TX_END_TIME_12 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_12 { get; set; }
        public string TX_VAC_TYPE_12 { get; set; }
        public string TX_START_DATE_13 { get; set; }
        public string TX_END_DATE_13 { get; set; }
        public string TX_START_TIME_13 { get; set; }
        public string TX_END_TIME_13 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_13 { get; set; }
        public string TX_VAC_TYPE_13 { get; set; }
        public string TX_START_DATE_14 { get; set; }
        public string TX_END_DATE_14 { get; set; }
        public string TX_START_TIME_14 { get; set; }
        public string TX_END_TIME_14 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_14 { get; set; }
        public string TX_VAC_TYPE_14 { get; set; }
        public string TX_START_DATE_15 { get; set; }
        public string TX_END_DATE_15 { get; set; }
        public string TX_START_TIME_15 { get; set; }
        public string TX_END_TIME_15 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_15 { get; set; }
        public string TX_VAC_TYPE_15 { get; set; }
        public string TX_START_DATE_16 { get; set; }
        public string TX_END_DATE_16 { get; set; }
        public string TX_START_TIME_16 { get; set; }
        public string TX_END_TIME_16 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_16 { get; set; }
        public string TX_VAC_TYPE_16 { get; set; }
        public string TX_START_DATE_17 { get; set; }
        public string TX_END_DATE_17 { get; set; }
        public string TX_START_TIME_17 { get; set; }
        public string TX_END_TIME_17 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_17 { get; set; }
        public string TX_VAC_TYPE_17 { get; set; }
        public string TX_START_DATE_18 { get; set; }
        public string TX_END_DATE_18 { get; set; }
        public string TX_START_TIME_18 { get; set; }
        public string TX_END_TIME_18 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_18 { get; set; }
        public string TX_VAC_TYPE_18 { get; set; }
        public string TX_START_DATE_19 { get; set; }
        public string TX_END_DATE_19 { get; set; }
        public string TX_START_TIME_19 { get; set; }
        public string TX_END_TIME_19 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_19 { get; set; }
        public string TX_VAC_TYPE_19 { get; set; }
        public string TX_START_DATE_20 { get; set; }
        public string TX_END_DATE_20 { get; set; }
        public string TX_START_TIME_20 { get; set; }
        public string TX_END_TIME_20 { get; set; }
        public Nullable<decimal> TX_DAY_HOURS_20 { get; set; }
        public string TX_VAC_TYPE_20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DT311_ACancelDayOffFormDetail> DT311_ACancelDayOffFormDetail { get; set; }
    }
}
