//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CBookingInfo
    {
        public string CONFERENCE_ROOM_CODE { get; set; }
        public string APPOINTMENT_DATE { get; set; }
        public string APPOINTMENT_START_USE_TIME { get; set; }
        public string APPOINTMENT_END_USE_TIME { get; set; }
        public string JOIN_USER_QTY { get; set; }
        public string CONFERENCE_NAME { get; set; }
        public string CONFERENCE_DIRECTOR { get; set; }
        public string APPLY_APPOINTMENT_EMP_CODE { get; set; }
        public string APPLY_APPOINTMENT_EMP_TEL { get; set; }
        public string PROJECTOR { get; set; }
        public string RECORDER { get; set; }
        public string MICROPHONE { get; set; }
        public string LASERPEN { get; set; }
        public string NEED_EQUIPMENT { get; set; }
        public string CONFERENCE_ROOM_LOCATION { get; set; }
        public string REMARK { get; set; }
        public string YN_USE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
