//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_CGetCar
    {
        public string EFORMSN { get; set; }
        public string CANCEL_EFORMSN { get; set; }
        public string USE_CAR_REASON { get; set; }
        public string DESTINATION_1 { get; set; }
        public string DESTINATION_2 { get; set; }
        public string DESTINATION_3 { get; set; }
        public string DESTINATION_4 { get; set; }
        public string START_USE_CAR_DATE { get; set; }
        public string START_USE_CAR_TIME { get; set; }
        public string END_USE_CAR_DATE { get; set; }
        public string END_USE_CAR_TIME { get; set; }
        public decimal MILEAGE { get; set; }
        public decimal USED_OIL_QTY { get; set; }
        public string DRIVER_EMP_CODE { get; set; }
        public string USE_CAR_EMP_CODE { get; set; }
        public string USE_CAR_DEPT_CODE { get; set; }
        public string CAR_NO { get; set; }
        public int PASSENGER_NO { get; set; }
        public string APPLICANT_SUID { get; set; }
        public string CAR_MANAGER_SUID { get; set; }
    }
}
