//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVYearTotal
    {
        public int OVERTIME_FEE_YEAR { get; set; }
        public decimal OVERTIME_FEE_YEAR_TBUDGET { get; set; }
        public decimal YEAR_TOTAL_REMNANT_FEE { get; set; }
        public decimal YEAR_TOTAL_HAPPEN_FEE { get; set; }
        public decimal CNYR_TOTAL_OVERTIME_FEE { get; set; }
        public int STAFF_TYPE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
