//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_AOvertimeDutyOffDetail
    {
        public string EFORMSN { get; set; }
        public int SN { get; set; }
        public string OVERTIME_EFORMSN { get; set; }
        public string OVERTIME_TYPE { get; set; }
        public string OVERTIME_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public Nullable<int> OVERTIME_HOURS { get; set; }
        public Nullable<int> ABLE_DUTYOFF_DAY_HOURS { get; set; }
        public Nullable<int> ALR_DUTYOFF_HOURS { get; set; }
        public Nullable<int> WANT_DUTYOFF_HOURS { get; set; }
        public string DUTYOFF_DL { get; set; }
        public string TX_SOURCE_TYPE { get; set; }
    }
}
