//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DSFToSalary
    {
        public string RELEASE_DATE { get; set; }
        public int SUBSIDY_TYPE_CODE { get; set; }
        public string SUBSIDY_TYPE_NAME { get; set; }
        public string EMP_CODE { get; set; }
        public int APPLY_AMOUNT { get; set; }
        public string APPLY_PERD { get; set; }
        public string REMARK { get; set; }
        public System.DateTime INCOME_DATA_GET_DATE { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
