//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT311_DOVBankDataD
    {
        public int OVERTIME_TYPE_CODE { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public int BATCH { get; set; }
        public string EMP_CODE { get; set; }
        public string OVERTIME_DATE { get; set; }
        public string EVENT { get; set; }
        public string OVERTIME_START_TIME { get; set; }
        public string OVERTIME_END_TIME { get; set; }
        public int OVERTIME_FEE_HOURS { get; set; }
        public int HOURS_SALARY { get; set; }
        public int STOT { get; set; }
        public string OVERTIME_KIND { get; set; }
        public decimal SHOULD_OFF_DAYS { get; set; }
        public decimal ALREADY_OFF_DAYS { get; set; }
        public decimal UN_OFF_DAYS { get; set; }
        public decimal ZSY_HOLIDAY_RESV_DAYS { get; set; }
        public int UN_REST_OVERTIME_FEE { get; set; }
        public int HOLIDAY_SUBSIDY { get; set; }
        public string UPDATE_STAFF { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
