//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dutyoff_HISTORY
    {
        public string empuid { get; set; }
        public string eformid { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string duty1 { get; set; }
        public string duty2 { get; set; }
        public string duty_absent { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string ok_flag { get; set; }
    }
}
