//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eforms
    {
        public string eformid { get; set; }
        public string frm_chinese_name { get; set; }
        public string organization_id { get; set; }
        public string eformtype { get; set; }
        public string frm_english_name { get; set; }
        public string screen_form_name { get; set; }
        public string parse_form_name { get; set; }
        public string write_form_name { get; set; }
        public string eformcata { get; set; }
        public Nullable<System.DateTime> design_time { get; set; }
        public string designer { get; set; }
        public Nullable<System.DateTime> last_modify_date { get; set; }
        public string onload_event { get; set; }
        public string onsubmit_event { get; set; }
        public string primary_table { get; set; }
        public string asp_filename { get; set; }
        public string userdefined_form { get; set; }
        public string submit_function { get; set; }
    }
}
