//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eform_event
    {
        public string employee_id { get; set; }
        public string eformid { get; set; }
        public string eform_type { get; set; }
        public System.DateTime begin_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string remark { get; set; }
        public string eformsn { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string gotoend { get; set; }
        public string totaldh { get; set; }
    }
}
