//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eformfields
    {
        public string fieldid { get; set; }
        public string eformid { get; set; }
        public string column_name { get; set; }
        public string display_type { get; set; }
        public string data_type { get; set; }
        public Nullable<int> data_len { get; set; }
        public string field_desc { get; set; }
        public string field_eng_desc { get; set; }
        public string view_type { get; set; }
        public Nullable<int> view_taborder { get; set; }
        public string user_profile { get; set; }
        public string already_define { get; set; }
        public string linkto { get; set; }
        public string allownull { get; set; }
        public string isprimarykey { get; set; }
        public string lookup_type { get; set; }
        public string lookup_text_var { get; set; }
        public string lookup_value_var { get; set; }
        public string onchange_event { get; set; }
        public string onclick_event { get; set; }
        public string create_column { get; set; }
        public string view_sortorder { get; set; }
        public string onblur_event { get; set; }
        public string table_name { get; set; }
        public string control_id { get; set; }
    }
}
