//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eformfieldsdummy
    {
        public string fieldid { get; set; }
        public string column_name { get; set; }
        public string display_type { get; set; }
        public string data_type { get; set; }
        public string create_column { get; set; }
        public string @readonly { get; set; }
        public string canmodify { get; set; }
        public string candisplay { get; set; }
        public string value { get; set; }
        public string isrequired { get; set; }
        public string toupper { get; set; }
        public string listbox { get; set; }
        public string control_id { get; set; }
    }
}
