//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eformStamp
    {
        public string eformsn { get; set; }
        public string stampsn { get; set; }
        public string STAMP_TITLE_NAME { get; set; }
        public string STAMP_EMP_NAME { get; set; }
        public string STAMP_TYPE { get; set; }
        public string STAMP_DATE { get; set; }
        public string STAMP_TIME { get; set; }
        public string YN_REPLACE { get; set; }
    }
}
