//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string EmpID { get; set; }
        public string EmpUID { get; set; }
        public string EmpName { get; set; }
        public string HomeAddr { get; set; }
        public string BirthDate { get; set; }
        public string ArrivedDate { get; set; }
        public string LeaveDate { get; set; }
        public string Office { get; set; }
        public string Rank { get; set; }
        public string SalType { get; set; }
        public string SalGrade { get; set; }
        public string SalPoint { get; set; }
        public string EmailAddr { get; set; }
        public string EmpType { get; set; }
        public string BloodType { get; set; }
        public string BirthPlace { get; set; }
        public string TimeGroup { get; set; }
        public string HolGroup { get; set; }
        public string WorkUnit { get; set; }
        public string CardNum { get; set; }
        public string IsWork { get; set; }
        public string IsErrand { get; set; }
        public string IsOvertime1 { get; set; }
        public string IsOverTime2 { get; set; }
        public string IsOverTime3 { get; set; }
        public Nullable<int> Seniority { get; set; }
        public Nullable<decimal> RestYear { get; set; }
        public Nullable<decimal> BusiYear { get; set; }
        public Nullable<decimal> SickYear { get; set; }
        public Nullable<decimal> RestRev1 { get; set; }
        public Nullable<decimal> RestRev2 { get; set; }
        public Nullable<decimal> RestPln { get; set; }
        public Nullable<decimal> RestPre { get; set; }
        public string Modifer { get; set; }
        public string ModifyDate { get; set; }
        public string AgentID1 { get; set; }
        public string AgentID2 { get; set; }
        public string AgentID3 { get; set; }
        public string IsDeposit { get; set; }
        public string BankID { get; set; }
        public string Accnt { get; set; }
        public string NotifyByEmail { get; set; }
        public string EMPEMAIL { get; set; }
    }
}
