//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow
    {
        public string eformid { get; set; }
        public int stepsid { get; set; }
        public Nullable<int> steps { get; set; }
        public Nullable<int> nextstep { get; set; }
        public string major_step { get; set; }
        public string pors { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public string group_id { get; set; }
        public string group_type { get; set; }
        public string allhandle { get; set; }
        public string canjump { get; set; }
        public string canback { get; set; }
        public string canadd { get; set; }
        public string candist { get; set; }
        public string candistcc { get; set; }
        public string canaddatt { get; set; }
        public string candelatt { get; set; }
        public string canconti { get; set; }
        public string bypass { get; set; }
        public string opinonly { get; set; }
        public Nullable<int> block { get; set; }
        public Nullable<int> layer { get; set; }
        public Nullable<int> tree { get; set; }
        public Nullable<int> backto_steps { get; set; }
        public string assign_column_id { get; set; }
        public string assigncc_column_id { get; set; }
        public string after_submit_proc { get; set; }
        public string when_receive_proc { get; set; }
        public string alias_group_name { get; set; }
        public string condi { get; set; }
        public string backcanassign { get; set; }
        public string backassign_column { get; set; }
        public string allowtempsave { get; set; }
        public string allowgotoend { get; set; }
        public string cansendmail { get; set; }
        public string overduenotice { get; set; }
        public Nullable<int> attachlimit { get; set; }
        public string allowdutyforgotoend { get; set; }
        public string gotoendcc { get; set; }
        public string canskip { get; set; }
    }
}
