//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flowcondition
    {
        public string eformid { get; set; }
        public int stepsid { get; set; }
        public int condition_no { get; set; }
        public int serial_no { get; set; }
        public string fieldid { get; set; }
        public string field_type { get; set; }
        public string condition_logic { get; set; }
        public string condition_type { get; set; }
        public string condition_values { get; set; }
        public string andor { get; set; }
        public Nullable<int> gotosteps { get; set; }
        public string condiassign { get; set; }
        public string condiassign_column { get; set; }
    }
}
