//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flowctl_history
    {
        public string flowsn { get; set; }
        public string eformid { get; set; }
        public string eformsn { get; set; }
        public Nullable<int> steps { get; set; }
        public string empuid { get; set; }
        public string emp_chinese_name { get; set; }
        public string group_name { get; set; }
        public Nullable<System.DateTime> hddate { get; set; }
        public string gonogo { get; set; }
        public string comment { get; set; }
        public Nullable<int> nextstep { get; set; }
        public Nullable<int> goback { get; set; }
        public string nextuser { get; set; }
        public Nullable<int> stepsid { get; set; }
        public string orgname { get; set; }
        public string important { get; set; }
        public Nullable<int> backto_steps { get; set; }
        public string iteration_uid { get; set; }
        public string next_iteration { get; set; }
        public Nullable<System.DateTime> recdate { get; set; }
        public string is_testmode { get; set; }
        public string duty_for { get; set; }
        public Nullable<System.DateTime> appdate { get; set; }
        public string filler { get; set; }
        public string subtype { get; set; }
        public string deptcode { get; set; }
        public string totaldh { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string AssistantUID { get; set; }
        public string ApplyDate { get; set; }
        public string RealDate { get; set; }
        public Nullable<System.DateTime> BackDate { get; set; }
        public string ButtonText { get; set; }
    }
}
