//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMSCDTYPE
    {
        public decimal SEQ_NO { get; set; }
        public string TYPE_CODE { get; set; }
        public string MAT_APPLY_TYPE_CD { get; set; }
        public string MAT_APPLY_TYPE_NM { get; set; }
        public string MAT_TYPE_CD { get; set; }
        public string MAT_TYPE_NM { get; set; }
        public string DEL_FLAG { get; set; }
        public string CREATE_DATE { get; set; }
        public string MODIFY_DATE { get; set; }
    }
}
