//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSdynamicsnapshotjobs
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.Guid pubid { get; set; }
        public System.Guid job_id { get; set; }
        public int agent_id { get; set; }
        public string dynamic_filter_login { get; set; }
        public string dynamic_filter_hostname { get; set; }
        public string dynamic_snapshot_location { get; set; }
        public int partition_id { get; set; }
        public bool computed_dynsnap_location { get; set; }
    }
}
