//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_metadataaction_request
    {
        public int tablenick { get; set; }
        public System.Guid rowguid { get; set; }
        public byte action { get; set; }
        public Nullable<long> generation { get; set; }
        public Nullable<int> changed { get; set; }
    }
}
