//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_supportability_settings
    {
        public Nullable<System.Guid> pubid { get; set; }
        public Nullable<System.Guid> subid { get; set; }
        public string web_server { get; set; }
        public int support_options { get; set; }
        public int log_severity { get; set; }
        public int log_modules { get; set; }
        public string log_file_path { get; set; }
        public string log_file_name { get; set; }
        public int log_file_size { get; set; }
        public int no_of_log_files { get; set; }
        public int upload_interval { get; set; }
        public int delete_after_upload { get; set; }
        public string custom_script { get; set; }
        public string message_pattern { get; set; }
        public Nullable<System.DateTime> last_log_upload_time { get; set; }
        public byte[] agent_xe { get; set; }
        public byte[] agent_xe_ring_buffer { get; set; }
        public byte[] sql_xe { get; set; }
    }
}
