//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_conflict_role_ADMINGROUPROLE
    {
        public string group_uid { get; set; }
        public string role_uid { get; set; }
        public string empuid { get; set; }
        public string emp_chinese_name { get; set; }
        public string employee_id { get; set; }
        public string rolename { get; set; }
        public string Org_ID { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<System.Guid> origin_datasource_id { get; set; }
    }
}
