//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_partition_groups
    {
        public int partition_id { get; set; }
        public short publication_number { get; set; }
        public Nullable<long> maxgen_whenadded { get; set; }
        public Nullable<bool> using_partition_groups { get; set; }
        public bool is_partition_active { get; set; }
    
        public virtual MSmerge_dynamic_snapshots MSmerge_dynamic_snapshots { get; set; }
    }
}
