//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_genhistory
    {
        public System.Guid guidsrc { get; set; }
        public Nullable<System.Guid> pubid { get; set; }
        public long generation { get; set; }
        public Nullable<int> art_nick { get; set; }
        public byte[] nicknames { get; set; }
        public System.DateTime coldate { get; set; }
        public byte genstatus { get; set; }
        public int changecount { get; set; }
        public int subscriber_number { get; set; }
    }
}
