//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_history
    {
        public Nullable<int> session_id { get; set; }
        public int agent_id { get; set; }
        public string comments { get; set; }
        public int error_id { get; set; }
        public byte[] timestamp { get; set; }
        public bool updateable_row { get; set; }
        public System.DateTime time { get; set; }
    }
}
