//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_replinfo
    {
        public System.Guid repid { get; set; }
        public bool use_interactive_resolver { get; set; }
        public int validation_level { get; set; }
        public long resync_gen { get; set; }
        public string login_name { get; set; }
        public string hostname { get; set; }
        public byte[] merge_jobid { get; set; }
        public int sync_info { get; set; }
    }
}
