//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        public string organization_id { get; set; }
        public string organization_desc { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createby { get; set; }
        public string leaderuid { get; set; }
        public string org_chinese_name { get; set; }
        public string org_english_name { get; set; }
        public string organization_type { get; set; }
    }
}
