//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmergeschemachange
    {
        public System.Guid pubid { get; set; }
        public Nullable<System.Guid> artid { get; set; }
        public int schemaversion { get; set; }
        public System.Guid schemaguid { get; set; }
        public int schematype { get; set; }
        public string schematext { get; set; }
        public byte schemastatus { get; set; }
        public int schemasubtype { get; set; }
    }
}
