//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcprfadm
    {
        public string yr { get; set; }
        public string salkind { get; set; }
        public decimal orprfamt { get; set; }
        public decimal inprfamt { get; set; }
        public decimal orspcamt { get; set; }
        public decimal inspcamt { get; set; }
        public decimal ortecprfamt { get; set; }
        public decimal intecprfamt { get; set; }
        public decimal orcopprfamt { get; set; }
        public decimal incopprfamt { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
