//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcrange
    {
        public string kind { get; set; }
        public string yr { get; set; }
        public string type { get; set; }
        public int ranges { get; set; }
        public int rangee { get; set; }
        public decimal pay { get; set; }
        public decimal par { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
