//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tctax
    {
        public decimal notax { get; set; }
        public decimal standard { get; set; }
        public decimal salsub { get; set; }
        public double taxrate { get; set; }
        public decimal taxmoney { get; set; }
        public decimal payment1 { get; set; }
        public double rate1 { get; set; }
        public decimal dispayment1 { get; set; }
        public decimal payment2 { get; set; }
        public double rate2 { get; set; }
        public decimal dispayment2 { get; set; }
        public decimal payment3 { get; set; }
        public double rate3 { get; set; }
        public decimal dispayment3 { get; set; }
        public decimal payment4 { get; set; }
        public double rate4 { get; set; }
        public decimal dispayment4 { get; set; }
        public decimal payment5 { get; set; }
        public double rate5 { get; set; }
        public decimal dispayment5 { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
