//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdassist
    {
        public int keyid { get; set; }
        public string empid { get; set; }
        public string payid { get; set; }
        public string payitem { get; set; }
        public string realym { get; set; }
        public string salyermon { get; set; }
        public decimal paydays { get; set; }
        public decimal payment { get; set; }
        public decimal tax { get; set; }
        public Nullable<System.DateTime> bankdate { get; set; }
        public string memo { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
        public string batchno { get; set; }
        public decimal dispayment { get; set; }
    }
}
