//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdcoopmedtax
    {
        public string taxorgcod { get; set; }
        public string medcod { get; set; }
        public string serno { get; set; }
        public string mark { get; set; }
        public string style { get; set; }
        public string idno { get; set; }
        public string idtyp { get; set; }
        public string subcod { get; set; }
        public string payamt { get; set; }
        public string taxamt { get; set; }
        public string netpay { get; set; }
        public string payman { get; set; }
        public string blank { get; set; }
        public string errcod { get; set; }
        public string payyear { get; set; }
        public string cname { get; set; }
        public string addr { get; set; }
        public string maddte { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
