//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdpemissal
    {
        public string dataorgid { get; set; }
        public string dataym { get; set; }
        public string tableid { get; set; }
        public string idnor5 { get; set; }
        public string offdeg { get; set; }
        public string saldeg { get; set; }
        public string salpnt { get; set; }
        public string title { get; set; }
        public string rate { get; set; }
        public string delmark { get; set; }
        public string idnol1 { get; set; }
        public string amount { get; set; }
        public string subtableid { get; set; }
        public string days { get; set; }
        public string area { get; set; }
        public string @class { get; set; }
        public string member { get; set; }
        public string salamt { get; set; }
        public string pubamt { get; set; }
        public string diff { get; set; }
        public string extraamt { get; set; }
        public string increatment { get; set; }
        public string currency { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string budget { get; set; }
        public string salpoint { get; set; }
        public string salrate { get; set; }
        public string pubpnt { get; set; }
        public string pubrate { get; set; }
        public string idnom25 { get; set; }
        public string advrate { get; set; }
        public string advamt { get; set; }
        public string blank { get; set; }
    }
}
