//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdsalary
    {
        public string salyermon { get; set; }
        public string realym { get; set; }
        public string empid { get; set; }
        public string paytype { get; set; }
        public string batchno { get; set; }
        public decimal basemon { get; set; }
        public decimal brwmon { get; set; }
        public string rankup { get; set; }
        public decimal orsalamt { get; set; }
        public decimal orsalamtadd { get; set; }
        public decimal insalamt { get; set; }
        public decimal insalamtadd { get; set; }
        public decimal orprfamt { get; set; }
        public decimal orprfamtadd { get; set; }
        public decimal inprfamt { get; set; }
        public decimal inprfamtadd { get; set; }
        public decimal orspcamt { get; set; }
        public decimal orspcamtadd { get; set; }
        public decimal inspcamt { get; set; }
        public decimal inspcamtadd { get; set; }
        public decimal ortecamt { get; set; }
        public decimal ortecamtadd { get; set; }
        public decimal intecamt { get; set; }
        public decimal intecamtadd { get; set; }
        public string tfctype { get; set; }
        public decimal tfcamt { get; set; }
        public decimal tfcamtadd { get; set; }
        public decimal travelcard { get; set; }
        public string instype { get; set; }
        public decimal insded { get; set; }
        public decimal insdeddel { get; set; }
        public decimal finded { get; set; }
        public decimal findeddel { get; set; }
        public decimal mbrded { get; set; }
        public decimal mbrdeddel { get; set; }
        public decimal wefded { get; set; }
        public decimal wefdeddel { get; set; }
        public decimal selfded { get; set; }
        public decimal selfdeddel { get; set; }
        public decimal pubded { get; set; }
        public decimal pubdeddel { get; set; }
        public decimal depded { get; set; }
        public decimal depdeddel { get; set; }
        public decimal insgrp { get; set; }
        public decimal insgrpdel { get; set; }
        public decimal labretselfded { get; set; }
        public decimal labretselfdeddel { get; set; }
        public decimal labretpubded { get; set; }
        public decimal labretpubdeddel { get; set; }
        public decimal tax { get; set; }
        public decimal taxdel { get; set; }
        public int workdays { get; set; }
        public int payhrs { get; set; }
        public string memo { get; set; }
        public Nullable<System.DateTime> bankdate { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
