//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporganizgroupre
    {
        public string organization_id { get; set; }
        public string group_idp { get; set; }
        public string group_idc { get; set; }
        public Nullable<int> display_order_c { get; set; }
        public string display_name_c { get; set; }
    }
}
