//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfsalary
    {
        public string realym { get; set; }
        public string empid { get; set; }
        public string paytype { get; set; }
        public string batchno { get; set; }
        public string salyermon { get; set; }
        public Nullable<System.DateTime> bgndate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public decimal relmon { get; set; }
        public decimal orsalamt { get; set; }
        public decimal insalamt { get; set; }
        public decimal orprfamt { get; set; }
        public decimal inprfamt { get; set; }
        public decimal orspcamt { get; set; }
        public decimal inspcamt { get; set; }
        public decimal ortecamt { get; set; }
        public decimal intecamt { get; set; }
        public decimal tfcamt { get; set; }
        public string instype { get; set; }
        public decimal insded { get; set; }
        public decimal finded { get; set; }
        public decimal mbrded { get; set; }
        public decimal wefded { get; set; }
        public decimal selfded { get; set; }
        public decimal pubded { get; set; }
        public decimal depded { get; set; }
        public decimal insgrp { get; set; }
        public decimal labretselfded { get; set; }
        public decimal labretpubded { get; set; }
        public decimal tax { get; set; }
        public string memo { get; set; }
        public Nullable<System.DateTime> bankdate { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
        public decimal orsalamtadd { get; set; }
        public decimal insalamtadd { get; set; }
        public decimal orprfamtadd { get; set; }
        public decimal inprfamtadd { get; set; }
        public decimal orspcamtadd { get; set; }
        public decimal inspcamtadd { get; set; }
        public decimal ortecamtadd { get; set; }
        public decimal intecamtadd { get; set; }
        public string mergesalym { get; set; }
    }
}
