//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfwsalary
    {
        public string realym { get; set; }
        public string empid { get; set; }
        public string paytype { get; set; }
        public string batchno { get; set; }
        public string salyermon { get; set; }
        public Nullable<System.DateTime> bgndate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public decimal relmon { get; set; }
        public string subject { get; set; }
        public string deptid { get; set; }
        public string title { get; set; }
        public string emptype { get; set; }
        public string salkind { get; set; }
        public string subkind { get; set; }
        public string saltype { get; set; }
        public string saldeg { get; set; }
        public int salpnt { get; set; }
        public decimal orsalamt { get; set; }
        public decimal insalamt { get; set; }
        public decimal orprfamt { get; set; }
        public decimal inprfamt { get; set; }
        public string spcadd { get; set; }
        public decimal orspcamt { get; set; }
        public decimal inspcamt { get; set; }
        public string tecadd { get; set; }
        public decimal ortecamt { get; set; }
        public decimal intecamt { get; set; }
        public decimal tfcamt { get; set; }
        public string instype { get; set; }
        public string insrate { get; set; }
        public decimal insmon { get; set; }
        public decimal insded { get; set; }
        public string finrate { get; set; }
        public decimal finmon { get; set; }
        public decimal finded { get; set; }
        public decimal mbrded { get; set; }
        public decimal wefded { get; set; }
        public decimal selfded { get; set; }
        public decimal pubded { get; set; }
        public decimal depded { get; set; }
        public decimal grpmon { get; set; }
        public decimal insgrp { get; set; }
        public decimal labretsalamt { get; set; }
        public string labretselfpcnt { get; set; }
        public decimal labretselfded { get; set; }
        public decimal labretpubpcnt { get; set; }
        public decimal labretpubded { get; set; }
        public decimal tax { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
        public string rankup { get; set; }
        public string discount { get; set; }
        public string agency { get; set; }
        public string agencyspc { get; set; }
        public string mergesalym { get; set; }
    }
}
