//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlsalary
    {
        public string realym { get; set; }
        public string salyermon { get; set; }
        public Nullable<System.DateTime> effdate { get; set; }
        public string empid { get; set; }
        public string paytype { get; set; }
        public string budget { get; set; }
        public string title { get; set; }
        public string deptid { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> arvdate { get; set; }
        public string edulevel { get; set; }
        public string daypay { get; set; }
        public string nopaymark { get; set; }
        public string nojobins { get; set; }
        public decimal agtbrwmon { get; set; }
        public string permisrnk { get; set; }
        public string permispag { get; set; }
        public string emptype { get; set; }
        public string salkind { get; set; }
        public string subkind { get; set; }
        public string saltype { get; set; }
        public string saldeg { get; set; }
        public int salpnt { get; set; }
        public decimal orsalamt { get; set; }
        public decimal insalamt { get; set; }
        public decimal orprfamt { get; set; }
        public decimal inprfamt { get; set; }
        public string spcadd { get; set; }
        public decimal orspcamt { get; set; }
        public decimal inspcamt { get; set; }
        public string tecadd { get; set; }
        public string tectitle { get; set; }
        public string teckind { get; set; }
        public decimal ortecamt { get; set; }
        public decimal intecamt { get; set; }
        public string tfctype { get; set; }
        public decimal tfcamt { get; set; }
        public string instype { get; set; }
        public decimal insmon { get; set; }
        public int insrate { get; set; }
        public string insdescr { get; set; }
        public string instranres { get; set; }
        public decimal insded { get; set; }
        public decimal finmon { get; set; }
        public string finrate { get; set; }
        public string findescr { get; set; }
        public string fintranres { get; set; }
        public decimal finded { get; set; }
        public decimal mbrded { get; set; }
        public decimal wefded { get; set; }
        public decimal selfded { get; set; }
        public decimal pubded { get; set; }
        public decimal depded { get; set; }
        public decimal insgrp { get; set; }
        public decimal tax { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
