//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmddct
    {
        public string salyermon { get; set; }
        public string empid { get; set; }
        public string ddcttype { get; set; }
        public decimal insded { get; set; }
        public decimal finded { get; set; }
        public decimal mbrded { get; set; }
        public string markym { get; set; }
        public string markid { get; set; }
        public decimal selfded { get; set; }
        public decimal pubded { get; set; }
        public decimal insgrp { get; set; }
        public decimal labretselfded { get; set; }
        public decimal labretpubded { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
