//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmemployee
    {
        public string empid { get; set; }
        public string cname { get; set; }
        public string idno { get; set; }
        public string empstatus { get; set; }
        public string budget { get; set; }
        public string errcode { get; set; }
        public string uid { get; set; }
        public string title { get; set; }
        public string deptid { get; set; }
        public string saldeptid { get; set; }
        public string subject { get; set; }
        public string marsts { get; set; }
        public int mbrnum { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<System.DateTime> bgndate { get; set; }
        public Nullable<System.DateTime> arvdate { get; set; }
        public Nullable<System.DateTime> levdate { get; set; }
        public string levwhy { get; set; }
        public string conaddr { get; set; }
        public string contel { get; set; }
        public string regaddr { get; set; }
        public string regtel { get; set; }
        public string email { get; set; }
        public string daypay { get; set; }
        public string edulevel { get; set; }
        public string edudesc { get; set; }
        public string gradym { get; set; }
        public string native { get; set; }
        public string nolocate { get; set; }
        public string idtype { get; set; }
        public string nopaymark { get; set; }
        public string memo { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
