//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmmedtax
    {
        public string taxorgcode { get; set; }
        public string medcode { get; set; }
        public string serno { get; set; }
        public string datacls { get; set; }
        public string inout { get; set; }
        public string snggrp { get; set; }
        public string typ { get; set; }
        public string typcls { get; set; }
        public string papamt { get; set; }
        public string subcod { get; set; }
        public string payment { get; set; }
        public string tax { get; set; }
        public string buscod { get; set; }
        public string blank1 { get; set; }
        public string houcod { get; set; }
        public string blank2 { get; set; }
        public string errcod { get; set; }
        public string year { get; set; }
        public string maddte { get; set; }
        public string strno { get; set; }
        public string endno { get; set; }
        public string selfpay { get; set; }
        public string zeromark { get; set; }
        public string blank3 { get; set; }
        public string source { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
        public string extra { get; set; }
    }
}
