//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmouttax
    {
        public decimal payid { get; set; }
        public System.DateTime paydate { get; set; }
        public string realym { get; set; }
        public string style { get; set; }
        public string idno { get; set; }
        public string payman { get; set; }
        public decimal payment { get; set; }
        public decimal tax { get; set; }
        public string recno { get; set; }
        public string memo { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
    }
}
