//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmretemp1
    {
        public string empid { get; set; }
        public string cname { get; set; }
        public string idno { get; set; }
        public string idtype { get; set; }
        public string rettype { get; set; }
        public string emptype { get; set; }
        public string salkind { get; set; }
        public string saltype { get; set; }
        public string saldeg { get; set; }
        public int salpnt { get; set; }
        public decimal orsalamt { get; set; }
        public decimal insalamt { get; set; }
        public string regaddr { get; set; }
        public string regtel { get; set; }
        public decimal oldpcnt { get; set; }
        public decimal newpcnt { get; set; }
        public string retpcnt { get; set; }
        public string stoppay { get; set; }
        public string crtuser { get; set; }
        public System.DateTime crtdate { get; set; }
        public string upduser { get; set; }
        public System.DateTime upddate { get; set; }
        public int oldyear { get; set; }
        public string newyear { get; set; }
        public int yearsum { get; set; }
        public decimal pcnt { get; set; }
    }
}
