//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoNotification
    {
        public string code { get; set; }
        public short serial { get; set; }
        public string unitname { get; set; }
        public string idn { get; set; }
        public string employee_id { get; set; }
        public string emp_chinese_name { get; set; }
        public string titlename { get; set; }
        public string computername { get; set; }
        public string computerip { get; set; }
    }
}
