//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class waithandle_HISTORY
    {
        public string empuid { get; set; }
        public string eformid { get; set; }
        public string frm_chinese_name { get; set; }
        public string flowsn { get; set; }
        public Nullable<System.DateTime> recdate { get; set; }
        public Nullable<System.DateTime> appdate { get; set; }
        public Nullable<System.DateTime> hddate { get; set; }
        public Nullable<System.DateTime> readdate { get; set; }
        public string applyer { get; set; }
        public string cc { get; set; }
        public string read2 { get; set; }
        public string important { get; set; }
        public string attach { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public string sender { get; set; }
        public string is_testmode { get; set; }
        public string employee_id { get; set; }
        public string duty_for { get; set; }
        public string subtype { get; set; }
        public string deptcode { get; set; }
        public string totaldh { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string AssistantUID { get; set; }
        public string applyerUids { get; set; }
        public string ApplyDate { get; set; }
        public string RealDate { get; set; }
        public Nullable<System.DateTime> BackDate { get; set; }
        public string ButtonText { get; set; }
    }
}
